### ISSUE TITLE
How to tell why package was 'removed'?

### ISSUE THREAD

**Issue by danmosemsft** [wbond/package_control#1036]
[My package](https://packagecontrol.io/packages/Web%20Inspector) is marked 'removed' and indeed it isn't offered in Sublime any more.

How can I tell why? It's possibly obvious but I don't see it, the [packages.json](https://github.com/sokolovstas/SublimeWebInspector/blob/master/packages.json) is still present, and the [same releases](https://github.com/sokolovstas/SublimeWebInspector/releases) as before.

Possibly related: a month or two ago I unwisely rewrote some pushed history. Never again. However, the commit pointed to by release [st3-1.7.4](https://github.com/sokolovstas/SublimeWebInspector/releases/tag/st3-1.7.4) still exists.

**Comment by danmosemsft** [comment]
Also odd, the [download graph](https://packagecontrol.io/packages/Web%20Inspector) continues normally. Unless the issue literally happened today, one would expect it to be zero...?

**Comment by wbond** [comment]
A package is considered removed if it hasn't been seen in 6 hours:

https://github.com/wbond/packagecontrol.io/blob/master/app/tasks/mark_removed.py
https://github.com/wbond/packagecontrol.io/blob/master/app/lib/removed_packages.py#L11-L57
https://github.com/wbond/packagecontrol.io/blob/master/app/models/package/find.py#L229-L244

From logging onto my server, it seems the crawler is getting taking about 2-4s per request to api.github.com. Normally it does probably 10+ per second. Because of this, it has fallen behind and can't keep up with crawling packages and packages that have stale info are being marked as removed.

I'm working on trying to resolve this now.

**Comment by wbond** [comment]
This was fixed last night and has been confirmed to still be fixed.

**Comment by danmosemsft** [comment]
Thanks Will. I wonder if it would be better to remove a package only if the repo was inaccessible for, say, a month. The owner could still remove it immediately if they wanted, by removing the package.json. 

That way if github does down for a while, packages don't start quickly disappearing.

**Comment by wbond** [comment]
I'd rather know something was wrong with the PC crawler after 6 hours than after a month. :smile:
