### ISSUE TITLE
Getting Popup - There are no packages available for installation

### ISSUE THREAD

**Issue by nishantmendiratta** [wbond/package_control#1059]
Following are the logs - 
Package Control: Fetching list of available packages
  Platform: linux-x64
  Sublime Text Version: 2221
  Package Control Version: 3.1.2

**Comment by just4play** [comment]
see https://github.com/wbond/package_control/issues/1057

**Comment by arvind07** [comment]
I am also having this issue on windows 8. Here is the log:

Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3083
  Package Control Version: 3.1.2
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.33.29
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug General
  Server SSL Certificate:
    subject: US, Massachusetts, Private Organization, 471714639, US, Massachusetts, Newbury, Codex Non Sufficit LC, codexns.io
    issuer: US, GeoTrust Inc., GeoTrust EV SSL CA - G4
    common name: codexns.io
    issue date: Thu, 29 Oct 2015 05:30:00 GMT
    expire date: Mon, 28 Nov 2016 05:29:59 GMT
Package Control: WinINet HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  User-Agent: Package Control v3.1.2
  Host: packagecontrol.io
  Connection: Keep-Alive
  Cache-Control: no-cache
  If-Modified-Since: Mon, 04 Jan 2016 09:00:02 GMT
  Accept-Encoding: gzip,deflate
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 304 Not Modified
  Server: nginx
  Date: Mon, 04 Jan 2016 09:06:39 GMT
  Last-Modified: Mon, 04 Jan 2016 09:00:02 GMT
  Connection: keep-alive
  ETag: "568a3492-5f"
  Strict-Transport-Security: max-age=15552000
Package Control: Using cached content for https://packagecontrol.io/channel_v3.json from C:\Users\ArvindX\AppData\Roaming\Sublime Text 3\Packages\User\Package Control.cache\01524fae79697630d0454ba3fabd9414
Package Control: WinINet HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request

**Comment by erickwilder** [comment]
+1 on this. I'm running MacOSX (El Capitan)
I completely removed all my plugins and did a fresh install of the Package Control and I'm still getting this error. There're no erros in the Sublime console:

```...
plugins loaded
Package Control: Installing 1 missing dependency
Package Control: The dependency specified, bz2, is not available
Package Control: Skipping automatic upgrade, last run at 2016-01-04 10:40:02, next run at 2016-01-04 11:40:02 or after```

**Comment by Reewr** [comment]
As mentioned by @just4play, the fix from #1057 by adding:
`https://web.archive.org/web/20160103232808/https://packagecontrol.io/channel_v3.json`
as a channel to package_control settings in Sublime fixed the issue for me.

**Comment by mhenrixon** [comment]
https://gist.github.com/mhenrixon/43f1254bf890bcec4714

**Comment by arvind07** [comment]
@Reewr Thats great.
For others:
Go to: Preferences -> Package Settings ->Package Control -> Settings - User

Add this at the end:
```
    "channels":
    [
        "https://web.archive.org/web/20160103232808/https://packagecontrol.io/channel_v3.json"
    ]
```

Now try to load packges by `ctrl + shift  + p`. It should work!

**Comment by nishantmendiratta** [comment]
Thanks @arvind07  it's working now !
