### ISSUE TITLE
The following incompatible dependency was found installed...

### ISSUE THREAD

**Issue by adisos** [wbond/package_control#1075]
After migrating to OSX this window always popping out:
![image](https://cloud.githubusercontent.com/assets/592907/12643676/cf2f7ae2-c5e7-11e5-896a-61c7390310c1.png)

The problem is I don't know what the 'User` plugin is.

**Comment by FichteFoll** [comment]
That looks very suspicious. Do you perhaps have a `dependency-metadata.json` file in your User package?

See http://docs.sublimetext.info/en/latest/basic_concepts.html#the-user-package

**Comment by wbond** [comment]
I believe this means some package listed `User` as a dependency, however Package Control could find no dependency-metadata.json in the User package.

@adisos What packages do you have installed?

**Comment by adisos** [comment]
User directory:
![image](https://cloud.githubusercontent.com/assets/592907/12650392/d62a1a1c-c60c-11e5-903b-fd48b5be6828.png)

Packages:
![image](https://cloud.githubusercontent.com/assets/592907/12650434/0a30a8bc-c60d-11e5-9508-a09a3a3d1eac.png)
![image](https://cloud.githubusercontent.com/assets/592907/12650514/52120496-c60d-11e5-9e60-30075664d45a.png)
![image](https://cloud.githubusercontent.com/assets/592907/12650623/ab91ef2c-c60d-11e5-9f54-4e130b4f4233.png)
![image](https://cloud.githubusercontent.com/assets/592907/12650641/be8f2946-c60d-11e5-877e-058f12440fda.png)
![image](https://cloud.githubusercontent.com/assets/592907/12650665/d64a57fe-c60d-11e5-929b-651d00b36451.png)
![image](https://cloud.githubusercontent.com/assets/592907/12650679/e0b1079c-c60d-11e5-919b-00e456d545cc.png)
![image](https://cloud.githubusercontent.com/assets/592907/12650690/e8c94584-c60d-11e5-9a8b-9dd44e42a284.png)

**Comment by claudiofrs** [comment]
I got this issue as well after linked User folder from Dropbox directory to Yosemite

**Comment by wbond** [comment]
So the code that shows this message is: https://github.com/wbond/package_control/blob/111fa929e065e14254e67d8103ebff877f3a7a00/package_control/package_cleanup.py#L288-L298

`invalid_dependencies` is pulled from `found_dependencies` if one is incompatible with the current platform or architecture: https://github.com/wbond/package_control/blob/111fa929e065e14254e67d8103ebff877f3a7a00/package_control/package_cleanup.py#L256-L272.

The only way a package gets into `found_dependencies` is if it is named `0_package_control_loader` or has a `.sublime-dependency` or `dependency-metadata.json` file in the folder: https://github.com/wbond/package_control/blob/111fa929e065e14254e67d8103ebff877f3a7a00/package_control/package_cleanup.py#L246-L249.

I think somehow you must have gotten a `.sublime-dependency` file in your `Packages/User/` folder. But also a `##-User.py` file must exist in `Installed Packages/0_package_control_loader.sublime-package`.

At least, that is the only way I can see this happening from reading the code.

@FichteFoll In this case, the dependency that is the issue is already listed (User). Thus, listing the package requiring the dependency (which is completely unknown in this part of the code) isn't really relevant for this case.

**Comment by MateuszKubuszok** [comment]
I had similar issue - User package as incompatible dependency when I had no `.sublime-dependency` there. If happened after I moved Windows installation into Linux. Running package control installation code again and restarting Sublime helped.

**Comment by genaDeus** [comment]
The same issue after moving from windows to linux. I've syncronized sublime as it was described here https://packagecontrol.io/docs/syncing. Only Data/Packages/User.

**Comment by wsszh** [comment]
@genaDeus Thanks a lot !

**Comment by lucasmartins** [comment]
Thanks @genaDeus, removing `Installed\ Packages/0_package_control_loader.sublime-package` has solved the problem for me. Also, I'm not syncing `Installed\ Packages` nor `Packages` (that's the source of the problem actually), with the exception of `Packages/Package\ Control*`.

This is my `.sync/IgnoreList` file now, for syncing between Mac and Linux machines (you can easily translate that for Dropbox or other syncing tools):
```
sublime/Installed\ Packages
sublime/Packages
!sublime/Packages/Package\ Control*
sublime/Packages/Package\ Control.cache
```
