### ISSUE TITLE
How to make P.C. to ignore custom installed package.

### ISSUE THREAD

**Issue by skyleet** [wbond/package_control#1080]
I am trying to installed a third party package(https://github.com/Robot-Will/Stino/tree/new-stino) by copying it to packages folder.
but whenever i start sublime text, Package Control moves the plugin folder to backup/2016XXXX
folder.
After disabling Package Control the Package works fine.
How can I make Package Control to ignore that package.

**Comment by wbond** [comment]
The issue is the package you are installing including a `package-metadata.json` file. It should not.

That file is generated by Package Control when it installs a package. The presence of such a file says to Package Control that it manages the package. Next, it looks in the `installed_packages` setting of `Package Control.sublime-settings` to see what packages are supposed to be installed. It then sees that `Stino` is not in that list, and removes the package.

This functionality exists to users may sync packages across machines, specifically syncing package removals.

To fix it, you need to get the plugin author to remove that file from the repo.

**Comment by skyleet** [comment]
Thanks.
I added "Stino-new-stino" to Control.sublime-settings and it was working fine.

**Comment by wbond** [comment]
The `package-metadata.json` present in the package may break things in unexpected ways in the future. I recommend opening an issue with the package author to remove that file from the repo.
