### ISSUE TITLE
Package Control silently deletes packages "incompatible" with current platform

### ISSUE THREAD

**Issue by jimbo1qaz** [wbond/package_control#1135]
Currently, I'm trying to get AutoHotkey package to not get deleted automatically on Linux. I tried changing the platforms to ["*"], renaming the package name, it still gets deleted.

This is a grave issue, because when I try to sync my Sublime folder between Windows and Linux, Package Control will silently delete packages incompatible with one platform, corrupting my profile without user consent, and preventing me from persistently installing the package on the other OS.

**Comment by wbond** [comment]
This is correct behavior, at least in so far as how Package Control was designed and implemented. Packages may have different versions for different platforms, versions of Sublime Text and CPU architectures. This is due to the fact that some code only works on certain platforms, and complied binaries are specific to the OS and architecture.

It sounds like you are trying to get Package Control to load a package on Linux that is not designed to work with Linux. This is generally a bad idea.

In terms of the technical implementation, there is a package-metadata.json file in the .sublime-package that contains info about the package and what it is compatible with. You would need to modify that to mark it as compatible with Linux. However, any time the package is upgraded, the metadata is rewritten.

If you are trying to sync packages, I'd recommend reading https://packagecontrol.io/docs/syncing.

**Comment by FichteFoll** [comment]
I will fix autohotkey to be compatible with all platforms since the most important part of it, syntax highlighting, is independent of platforms.

**Comment by wbond** [comment]
I don't think there is anything else to do here.

**Comment by jimbo1qaz** [comment]
If I can't sync the Installed/Packages folders, how do I write my own small packages and sync them across my machines?

It seems like Package Control insists on controlling all package state, without allowing users to manually override, manage, or install packages. (I literally disabled Package Control for a month over this.)

**Comment by FichteFoll** [comment]
You should use the User package for this, unless you're overriding package ressources.

**Comment by wbond** [comment]
@jimbo1qaz In short, Package Control won't touch anything without a `package-metadata.json`. Don't place that in your packages and PC won't touch them. You can sync them all you want. :-)

If you really wanted to, you could add it all to a GitHub repo, then add that as a Package Control repository on each of your machines and Package Control will keep them up-to-date with each other.

**Comment by FichteFoll** [comment]
The AutoHotkey package is now installable on all platforms.
