### ISSUE TITLE
Package control deletes packages without confirmation

### ISSUE THREAD

**Issue by rornor** [wbond/package_control#1149]
Hi,

your plugin deleted my SFTP package. Afterwards I found it in backups and did restore, but yet again your plugin deleted my SFTP package. I removed Package control to be on a safe side, however I'm interested why your plugin deletes packages without confirmation and then what is the reason for deleting SFTP plugin?

**Comment by wbond** [comment]
Package Control only deletes a package if it was synced improperly from another machine. It uses a combination of the `installed_packages` setting in `User/Package Control.sublime-settings` and the `SFTP/package-metadata.json` file to determine if Package Control actually installed the package or not.

If a package was installed manually, it will have neither. If a package was synced/copied from a machine with Package Control onto another machine, Package Control will see it is not supposed to be installed because it is not present in `installed_packages` and it will delete it.

You should see a message like `Removed directory for orphaned package` in your console. This indicates what I described above is actually happening.

**Comment by rornor** [comment]
Ok, thanks for your explanation.

I won't drill into it, as it's your scheme, but can you please respect readonly status, and avoid deleting such folders? It's because you don't even provide confirmation and delete anything you find not confirming to your work scheme.

Thanks

**Comment by wbond** [comment]
I don't currently have plans to add such a feature. I would recommend not adding Package Control metadata to packages that you are not managing with Package Control.

**Comment by rornor** [comment]
Ok, thanks for your fast reply

**Comment by wbond** [comment]
Specifically, make sure you don't have a `package-metadata.json` file in packages you want Package Control to leave alone. That file means the package was installed by Package Control, so it should manage it.
