### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by tejaskhot** [wbond/package_control#1188]
I am not able to open the website https://packagecontrol.io/ in either Chrome or Firefox and get the following error:
```
This site can’t be reached

packagecontrol.io refused to connect.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
```

**Comment by alanwei0** [comment]
me too

**Comment by yuuuuwwww** [comment]
Same here

**Comment by a-zhunusbekov** [comment]
Same here

**Comment by Kristinita** [comment]
If you understand Russian language, see [my answer](http://ru.stackoverflow.com/a/479690/199934) on Russian Stack Overflow, what you need to make if Package Control site is down. Thanks.

**Comment by seemsindie** [comment]
+1

**Comment by tomkenta** [comment]
same here.

**Comment by stondo** [comment]
+1

**Comment by athrunsun** [comment]
@Kristinita Could you give a brief explanation in English in this thread please?

**Comment by universal** [comment]
ctrl+shift+p -> package control: add channel -> Enter the following url: ```https://web.archive.org/web/20160410055050/https://packagecontrol.io/channel_v3.json```

Afterwards it loads old packages, so once it is up again, you should remove it again! Either manually through settings -> package control -> ... user or through the menu and remove channel :-)

**Comment by kosick** [comment]
+1

**Comment by Kristinita** [comment]
# Question for JavaScript or others programmers

May someone to complement code of [WebCite Archive](https://greasyfork.org/ru/scripts/19361-webcite-archive-vivre/code) Firefox addon?

## What for?

It would be nice, if Package Control site is down, users may download the newest version of packages use Package Control.

We need [add alternative channel](http://ru.stackoverflow.com/a/479690/199934), but latest version in Internet Archive date only [April 2016](https://web.archive.org/web/20160410055050/https://packagecontrol.io/channel_v3.json). We can not download the newest packages and versions of packages from alternative channel.

But we can write script, add copies of `channel_v3.json` file on [Archive.is](http://archive.is/), [Internet Archive](https://archive.org/index.php) and [WebCite](http://webcitation.org/) sites every day, and users can download the newest versions of packages if Package Control site is down.

## How now to work WebCite Archive?

I add in WebCite Archive code own preferences, for example:

```javascript
var myMail = 'example@example.com';		//  change to your e-mail

var useMail_Single = 1;		//  0/1 dis-/enable usage of your mail for single page request
var useMail_Multi = 1;		//  0/1 dis-/enable usage of your mail for multiple page requests

var maxPages = 20;		// maximum processed links per function-call [submit], encrease at own risk
```

Left click to GreaseMonkey arrow button → `User Script commands...` → `WebArchive Multi-url` → I insert one or multiple links in textarea field → `submit links to webcitation` → links was saved on WebCite site.

![WebCite Archive](http://i.imgur.com/Sfoch0A.gif)

And in my e-mail I get messages. Example:

	Your recent WebCite request has completed. Following are the results from this request:

	--------------------------------------
	SUCCESSFULLY CACHED

	https://github.com/Kristinita/SashaSublime

	Please use the URL http://www.webcitation.org/6lxIOAJcW to access the cached copy of this page
	--------------------------------------

	Thank your for using WebCite for archiving! If you are interested in keeping this service alive, please support us by giving donations http://fnd.us/c/aQMp7 

	 Please give generously - or at least share our campaign on Facebook. Funders supporting us with $250 or more will be mentioned in any future services. http://fnd.us/c/aQMp7


	If you have any questions, please feel free to contact the WebCite team at http://www.webcitation.org

	Regards,

	The WebCite Team

Now I can run macro and send copy of https://packagecontrol.io/channel_v3.json web-page to WebCite every day, use task scheduler (for example, I use [nnCron](https://github.com/nnCron/nnCron#nncron-en)).

## Why WebCite Archive now is bad?

WebCite Archive is worked script, but this script add archive copies of pages only in WebCite — bad site, which have many bugs and often does not work. Archive.is and Internet Archive also have disadvantages, see [details](https://greasyfork.org/ru/forum/discussion/9391/x).

But if we copied web pages at once all 3 services, not only one service, it will be better, because 1 of 3 sites must work, when we make a copy of web-page.

Thanks.

**Comment by momoca** [comment]
https://status.linode.com/incidents/z276q20qgn67

**Comment by tejaskhot** [comment]
The site is up again, closing the issue.
