### ISSUE TITLE
Chai completions package shows missing

### ISSUE THREAD

**Issue by seethroughtrees** [wbond/package_control#1194]
I authored [Chai Completions](https://github.com/seethroughtrees/sublime-chai-full-completions) plugin a couple years back, and just got an issue saying that it was missing.  

I do see that at as well: https://packagecontrol.io/packages/Chai%20Completions

However, the github links appear correct, and so does the link to the repo in `repository/c.json`.

I no longer use Sublime Text, but would like to keep the package available for users who can use it.

Can someone please advise what I can do to get it working again?

**Comment by FichteFoll** [comment]
A git blame revealed that @hc-12 has accidentally changed the release discovery of your package to use tags (https://github.com/wbond/package_control_channel/pull/5518), but you do not have any tags specified in your repository. This is also explained by hovering the "Missing" indicator on the website.

Your best option for fixing it would be just create and push a tag name `v1.0.0` to the package's repository.

Sorry for not noticing this change, since it would have been my job to prevent this from happening.

**Comment by seethroughtrees** [comment]
No problem at all.  Added tag on my side.  Please let me know if anything else is required.  Thanks!

**Comment by seethroughtrees** [comment]
Appears to work as expected now.  Thanks!
