### ISSUE TITLE
Package Control cannot install packages because of CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by vrdabomb5717** [wbond/package_control#1208]
As a few others have reported, I can't install any packages in Package Control. I've created a new issue because the others seemed to talk about other issues (#1195 is about ignored packages, #1159 is about Windows issues, and #1163 is about a proxy using different certs).

My network doesn't use proxies, Package Control is not on my list of ignored packages, and I'm using MacOS Sierra, not Windows. I followed the instructions at https://packagecontrol.io/docs/troubleshooting#There_are_no_packages_available_for_installation and https://packagecontrol.io/docs/troubleshooting#Purging_and_Reinstalling . Neither seem to work.

To try and debug this, I took the root cert for https://packagecontrol.io/channel_v3.json and added it to my `Package Control.user-ca-bundle`, but that still doesn't seem to work either. The root cert is definitely in the merged bundle, but isn't getting picked up when trying to fetch the list of packages.

## User sublime settings

```
// Settings in here override those in "Default/Preferences.sublime-settings",
// and are overridden in turn by syntax-specific settings.
{
	
}
```

## GeoTrust Global CA.pem (root cert for channel_v3.json)

```
-----BEGIN CERTIFICATE-----
MIIDVDCCAjygAwIBAgIDAjRWMA0GCSqGSIb3DQEBBQUAMEIxCzAJBgNVBAYTAlVT
MRYwFAYDVQQKEw1HZW9UcnVzdCBJbmMuMRswGQYDVQQDExJHZW9UcnVzdCBHbG9i
YWwgQ0EwHhcNMDIwNTIxMDQwMDAwWhcNMjIwNTIxMDQwMDAwWjBCMQswCQYDVQQG
EwJVUzEWMBQGA1UEChMNR2VvVHJ1c3QgSW5jLjEbMBkGA1UEAxMSR2VvVHJ1c3Qg
R2xvYmFsIENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2swYYzD9
9BcjGlZ+W988bDjkcbd4kdS8odhM+KhDtgPpTSEHCIjaWC9mOSm9BXiLnTjoBbdq
fnGk5sRgprDvgOSJKA+eJdbtg/OtppHHmMlCGDUUna2YRpIuT8rxh0PBFpVXLVDv
iS2Aelet8u5fa9IAjbkU+BQVNdnARqN7csiRv8lVK83Qlz6cJmTM386DGXHKTubU
1XupGc1V3sjs0l44U+VcT4wt/lAjNvxm5suOpDkZALeVAjmRCw7+OC7RHQWa9k0+
bw8HHa8sHo9gOeL6NlMTOdReJivbPagUvTLrGAMoUgRx5aszPeE4uwc2hGKceeoW
MPRfwCvocWvk+QIDAQABo1MwUTAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTA
ephojYn7qwVkDBF9qn1luMrMTjAfBgNVHSMEGDAWgBTAephojYn7qwVkDBF9qn1l
uMrMTjANBgkqhkiG9w0BAQUFAAOCAQEANeMpauUvXVSOKVCUn5kaFOSPeCpilKIn
Z57QzxpeR+nBsqTP3UEaBU6bS+5Kb1VSsyShNwrrZHYqLizz/Tt1kL/6cdjHPTfS
tQWVYrmm3ok9Nns4d0iXrKYgjy6myQzCsplFAMfOEVEiIuCl6rYVSAlk6l5PdPcF
PseKUgzbFbS9bZvlxrFUaKnjaZC2mqUPuLk/IH2uSrW4nOQdtqvmlKXBx4Ot2/Un
hw4EbNX/3aBd7YdStysVAq45pmp06drE57xNNB6pXE0zX5IJL4hmXXeXxx12E6nV
5fEWCRE11azbJHFwLJhWC9kXtNHjUStedejV0NxPNO3CBWaAocvmMw==
-----END CERTIFICATE-----
```

## Package Control Debug logs

```
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3126
  Package Control Version: 3.2.1
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.34.243
  Resolved IPv6: 2600:3c02:e000:42::1
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at /Users/Varun/Library/Application Support/Sublime Text 3/Packages/User/oscrypto-ca-bundle.crt (270135 bytes)
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at /Users/Varun/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
Package Control: Error downloading channel. HTTP exception InvalidCertificateException (Host packagecontrol.io returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548))) downloading https://packagecontrol.io/channel_v3.json.
```

**Comment by debasis123** [comment]
same problem :(

**Comment by gracedigital** [comment]
experiencing same problem as debasis123 on macOS Sierra 10.12.3.

**Comment by qmarcos** [comment]
the same here, macOS El Capitan 10.11.5

**Comment by bijection** [comment]
Same here.

```
Package Control: Error downloading channel. 
HTTP exception InvalidCertificateException 
(Host packagecontrol.io returned an invalid certificate 
    ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:550))) 
downloading https://packagecontrol.io/channel_v3.json.
```

**Comment by onnimonni** [comment]
I enabled `"debug": true` and saw this line in the console before the `InvalidCertificateException` error:
```
Package Control: Found previously exported CA bundle at /Users/onnimonni/Library/Application Support/Sublime Text 3/Packages/User/oscrypto-ca-bundle.crt (318952 bytes)
```

I deleted the `oscrypto-ca-bundle.crt` file and my problems wen't away:
```
$ rm "/Users/$USER/Library/Application Support/Sublime Text 3/Packages/User/oscrypto-ca-bundle.crt"
```

**Comment by gracedigital** [comment]
I did that as well but only resolved the problem temporarily.  The most durable solution I have found unfortunately is to manually install packages right now.

**Comment by spanishgringo** [comment]
I tried removing the crt file and it didn't change anything. Still can't install or update any packages. macOS 10.12.3

**Comment by wbond** [comment]
Just today I wrapped up asn1crypto 0.21.0 and oscrypto 0.18.0, which will allow me to hook into the certificate export process to help us debug which certificates are being exported, and which are failing.

I'm also considering writing a simple TLS debugger using `oscrypto.tls.TLSSocket()` since it exposes the entire certificate chain, and will allow me to print a complete list of all cert info returned by the server. The only downside is that the issue may only be present with OpenSSL, and not when using SecureTransport on OS X.

**Comment by spanishgringo** [comment]
Let me know if there is anything you'd like me to test on my end.  BTW, I tried only using curl (based on suggestion I saw on https://forum.sublimetext.com/t/st3-3126-package-control-ssl-cert-invalid-errors-reinstall-didnt-help/23539/9) and that didn't make any difference for me.

**Comment by spanishgringo** [comment]
Any update on this issue?

**Comment by jonluca** [comment]
Still encountering this issue

**Comment by jonluca** [comment]
Fixed it with #1220

**Comment by bijection** [comment]
Thanks @jonluca! That worked for me as well.

**Comment by qmarcos** [comment]
Worked for me too! Thanks a lot @jonluca

**Comment by avelis** [comment]
Thanks again for the solution. I made a [comment in #1220](https://github.com/wbond/package_control/issues/1220#issuecomment-300367747) to help others understand the solution a little easier.

**Comment by vrdabomb5717** [comment]
Worked for me. Thanks!

**Comment by eeerrrttty** [comment]
Got this error: 

`    [105/427] CC build/release/obj/client_protocol/server.o
src/client_protocol/server.cc: In member function ‘size_t http_conn_cache_t::sha_hasher_t::operator()(const conn_key_t&) const’:
src/client_protocol/server.cc:177:16: error: aggregate ‘EVP_MD_CTX c’ has incomplete type and cannot be defined
     EVP_MD_CTX c;
                ^
src/build.mk:390: recipe for target 'build/release/obj/client_protocol/server.o' failed
make[1]: *** [build/release/obj/client_protocol/server.o] Error 1
Makefile:52: recipe for target 'make' failed
make: *** [make] Error 2
`

**Comment by jonluca** [comment]
@eeerrrttty are you on the right issue? This issue doesn't have anything to do with compilation or `make`, so I'm not seeing how they're related. Did you see this in the `package_control` terminal window?

**Comment by eeerrrttty** [comment]
Whell, im really sorry, i pasted the wrong ctrl+C. The error i got was that:

`startup, version: 3083 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /root/.config/sublime-text-3/Packages
state path: /root/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /root/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 2.12291
startup time: 4.04149
first paint time: 4.05478
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
plugins loaded
recreating index
unable to auto detect encoding for ~/matlab_2017_linux/0DayDown.htm, using fallback encoding Western (Windows 1252)
>>>  import urllib.request,os,hashlib; h = '6f4c264a24d933ce70df5dedcf1dcaee' + 'ebe013ee18cced0ef93d5f746d80ef60'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by) 
  File "<string>", line 1
    import urllib.request,os,hashlib; h = '6f4c264a24d933ce70df5dedcf1dcaee' + 'ebe013ee18cced0ef93d5f746d80ef60'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by) 
    ^
IndentationError: unexpected indent
>>>  import urllib2,os,hashlib; h = '6f4c264a24d933ce70df5dedcf1dcaee' + 'ebe013ee18cced0ef93d5f746d80ef60'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); os.makedirs( ipp ) if not os.path.exists(ipp) else None; urllib2.install_opener( urllib2.build_opener( urllib2.ProxyHandler()) ); by = urllib2.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); open( os.path.join( ipp, pf), 'wb' ).write(by) if dh == h else None; print('Error validating download (got %s instead of %s), please try manual install' % (dh, h) if dh != h else 'Please restart Sublime Text to finish installation') 
  File "<string>", line 1
    import urllib2,os,hashlib; h = '6f4c264a24d933ce70df5dedcf1dcaee' + 'ebe013ee18cced0ef93d5f746d80ef60'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); os.makedirs( ipp ) if not os.path.exists(ipp) else None; urllib2.install_opener( urllib2.build_opener( urllib2.ProxyHandler()) ); by = urllib2.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); open( os.path.join( ipp, pf), 'wb' ).write(by) if dh == h else None; print('Error validating download (got %s instead of %s), please try manual install' % (dh, h) if dh != h else 'Please restart Sublime Text to finish installation') 
    ^
IndentationError: unexpected indent
>>>  import urllib.request,os,hashlib; h = '6f4c264a24d933ce70df5dedcf1dcaee' + 'ebe013ee18cced0ef93d5f746d80ef60'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by) 
  File "<string>", line 1
    import urllib.request,os,hashlib; h = '6f4c264a24d933ce70df5dedcf1dcaee' + 'ebe013ee18cced0ef93d5f746d80ef60'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by) 
    ^
IndentationError: unexpected indent
`
Was in sublime, went to 'console', tried the command:

` import urllib.request,os,hashlib; h = '6f4c264a24d933ce70df5dedcf1dcaee' + 'ebe013ee18cced0ef93d5f746d80ef60'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by) `

**Comment by FichteFoll** [comment]
Make sure to remove any leading whitespaces before the command in the input.

**Comment by zephyringOG** [comment]
Found a working solution for my case. Sublime -> Preferences -> Package Settings -> Package Control -> Settings Default, in the downloader_precedence, add `curl` as preferred method.
