### ISSUE TITLE
[Feature Request] allow adding a Git Repository that contains multiple packages as root folders

### ISSUE THREAD

**Issue by keith-hall** [wbond/package_control#1230]
I really like Package Control's ability to install a package from a Git repo, and keep it updated.

I was thinking recently, that it'd be super awesome if it could also work with Git repos that contain multiple packages as subfolders, like the [SublimeHQ Packages repo](https://github.com/sublimehq/Packages) (and forks of it). As these shipped packages are not otherwise auto-updated outside of a new ST build being released, it would be really helpful if Package Control could assist in this regard.

I imagine it could work exactly as it does now, but just create multiple `.sublime-package` files in the `Installed Packages` folder - one per subfolder in the repo (instead of one `.sublime-package` file based on the repo's name). When ST encounters a `.sublime-package` file in the `Installed Packages` folder with the same name as one of the shipped packages in the ST installation directory, it simply ignores the one in the installation directory, which is what we want in this case. Any custom overrides the user has(, if they even have any), will still work as normal, and so is unlikely to cause any problems or lost work. (Besides, people creating overrides should be using [OverrideAudit](https://forum.sublimetext.com/t/overrideaudit/27066) anyway.)

As the SublimeHQ Packages repo is designed to only be used on the latest ST Dev build, syntaxes/packages from that repo could become unusable if Package Control updates them on older builds, so my proposal would be to simply only auto-update packages from this repo when the latest ST Dev build is being used.

---

I'm more than happy to work on this feature myself, but I wanted to file an issue here to gather feedback. For example, would it matter if Package Control updates `.sublime-package` files even when that subfolder had no changes since the previous update, or would it be preferable if we build some solution to only update packages that have changes? Bearing in mind how GitHub's last modified date/time in it's repo ZIP files works, the latter may require quite some work.

Also, do we want a generic solution that will work for other repos that contain multiple subfolders as packages, or is it okay to assume it will be the Shipped Packages repo or a fork of it? If we go down the generic route, we will need to think about how/when to enforce the "latest dev build" requirement, if we decide to go for that.

**Comment by OdatNurd** [comment]
I think something like this is definitely a good idea. It would be interesting to know what the "official" plans might be for getting updates for the default packages once ST3 is released. I assume that enhancements will still be made (ST4 maybe?), so will there be a schedule of releases to get those changes out, for example?

On the matter of package by package updates. if e.g. `HTML.sublime-package` got updated every time something else was updated, OverrideAudit would produce warnings if the user had any overrides in place, which could potentially get annoying quickly. From that perspective, only updating a package if there are any changes in that part of the tree since last time seems more "in scope" for everything.

On the other hand if packages were being frequently updated, perhaps there would be no need for such overrides in the first place? Those packages could also be added to the list of packages to ignore, although that would block potential problems from being discovered as well.

**Comment by FichteFoll** [comment]
I am personally pretty neutral on this matter. For example, I selectively symlink packages to my cloned git repo, which I keep under control myself, so I don't have a need for it myself. This also allows me to stay away from branches that contain changes requiring a new unreleased build. I believe that most of the outstanding issues have been ironed out with 3127, but things may change again. There are still a couple issue with feature requests or bug reports regarding syntax highlighting on the Core repo and potentially any of them could indirectly lead to a breaking change that PC would install. For dev builds, this is usually not too much of an issue, since @wbond mostly merges these braking changes shortly before a new release. However, this becomes more prevelant with **beta builds**, as it can take a few weeks/months until the next beta build surfaces from the latest dev sprint. The initial addition of the sublime-syntax format took quite a long time to land in beta, for example.
Your solution to only auto-update when you're on the latest dev build touches this area and is a servable work-around, as long as it allows installation on beta builds regardless (since most users are using those). Otherwise we might as well not bother at all.

Regarding your questions:

1. I don't really care. I'll leave this to the person implementing it whether it's worth to invest this extra time. For example, updating on any change could lead to conflicts with OverrideAudit, as @OdatNurd outlined, otherwise.

2. Because we are special-casing *a lot* here (the Packages repo is the only one that could ever contain backwards-incompatible changes with *all* currently released builds) and it has never been requested before iirc, I suggest to only implement this for the default packages.

**Comment by evandrocoan** [comment]
> I imagine it could work exactly as it does now, but just create multiple .sublime-package files in the Installed Packages folder - one per subfolder in the repo (instead of one .sublime-package file based on the repo's name).

This seems a very nice idea to allow easily install the `Sublimehq/Packages` packages, in contrast to putting each of the repositories into a submodule. Until now I never had though about allowing this kind of installation. The implementation should long. I would propose the following approach:
1. Let us suppose I want to install the `Sublimehq/Packages`
1. The `Sublimehq/Packages` should define a file to tell `Package Control` that the package is not a usual package and each folder inside it should be installed as a different `.sublime-package`. We can create a file called `.sublime-packages` on the root of the `Sublimehq/Packages` folder to sign this.
1. First package Control should install `Sublimehq/Packages` as a normal package
1. Once the installation is completed, a new module should run and look for the `.sublime-packages` file on the root of the `Sublimehq/Packages` folder.
1. If it found this file, then it starts the unpacking re-repacking process:
    1. This should mark all the packages on the `Sublimehq/Packages` (including `Sublimehq/Packages`) as installed packages
    1. Add them all to the `ignored_packges` list
    1. Wait 1.7 seconds
    1. Unpack the `Sublimehq/Packages` package and zip each folder as a `sublime-package`
    1. Hashes each one of the `Sublimehq/Packages`
    1. Save each hash on some settings folders it can access later
    1. Unignore the ignored packages
    1. Delete the `Sublimehq/Packages.sublime-package`
1. Now when updating, the packages, the process should be:
    1. Update the `Sublimehq/Packages` as it updates any other package, except this package is never present on disk, then the `dependency-metadata.json` should be saved elsewhere where it can be accessed later
    1. Unpack the `Sublimehq/Packages` package and zip each folder as a `sublime-package`
    1. Hashes each one of the `Sublimehq/Packages`
    1. Check each saved hash on settings folders it used before with the current hashes
    1. Add all the packages which the hash did not matched to the `ignored_packges` list
    1. Wait 1.7 seconds
    1. Replace the `.sublime-packages`
    1. Unignore the ignored packages
    1. Delete the `Sublimehq/Packages.sublime-package`
1. Loose files on the `Sublimehq/Packages` repository are just ignored during this process.

This algorithm should have several unpredictable flaws, which can be addressed while implementing it. For now I do not think I am interested it implemented it, because I think that the idea of putting several packages at one repository is not a nice idea, as would be be hard to distinguish/tell/track each own package git history, if everything is gathered together at one big mother repository.

I think it is more properly organized to put each of the the default packages on `Sublimehq/Packages` on theirs own repository and let Package Control to install them as any other packages. This one should not be hard to do, and when I got bugged enough, I am going to implement this one with my fork of `Sublimehq/Packages`. 

In order to keep sync with the upstream `Sublimehq/Packages` I would have to do a nasty thing of keeping both repositories actively in sync, i.e., when updates are received on the `Sublimehq/Packages`, it would be needed/required to do a commit on each submodule/repository of `Sublimehq/Packages`.

This is why I think that your idea is nicer than this alternative, as it should be hard to keep track of changes on `Sublimehq/Packages` and each submodule. This would lead to a horrible commit history on the submodules, because the commits would be all like `Updates from upstream for build 3166`. Anyways, it easily allow to distribute the default packages by package control as it is currently implemented.

**Comment by mataha** [comment]
*grabs a shovel*

I am interested in making this happen; however, I'm not sure if the approach I have in mind is in line with what's been already proposed in this thread, as I don't see a reason not to treat each package in a monorepo independently. I apologize in advance if any of the ideas below happens to be impossible to implement as I haven't delved that deep into the internal workings of PC.

Currently, adding a repository to the default channel requires the following (taken from [here](https://packagecontrol.io/docs/submitting_a_package#Step_6)):

```json
{
    "name": "Alignment",
    "details": "https://github.com/wbond/sublime_alignment",
    "releases": [
        {
            "sublime_text": "*",
            "tags": true
        }
    ]
}
```

I propose allowing `details` to accept an object that would consist, in a fashion similar to that of [package.json](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#repository), of the following:

```json
{
    "name": "Alignment",
    "details": {
        "type": "git",
        "url": "https://github.com/wbond/sublime_alignment",
        "directory": "."
    },
    "releases": [
        {
            "sublime_text": "*",
            "tags": true
        }
    ]
}
```

 - `url` - **Required.** URL to the public repository containing the package. Serves the same function as `details` does now.
 - `directory` - **Optional** (*default*: `.`). Specifies the directory in which the package lives if it's not in the root of a repository. As Package Control doesn't define any marker files (such as `.sublime-packages` proposed above), this would serve as the single source of truth. Determining whether a package update is necessary would be as simple as `git log -- <directory>` or through hashing as proposed above (but this is an implementation detail anyway).
 - `type` - **Optional** (*default*: `git`). VCS to use. *Probably unnecessary as Package Control doesn't support nor doesn't plan to support VCS other than git, but I'm including this for completeness with the package.json example.*

I would be willing to help implement this, but I'd like to hear some feedback first.

**Comment by deathaxe** [comment]
The best option to organize multiple packages in a single repository is probably to create a Github Actions runner which checks out the repo, creates download artefacts and related repository.json containing version information for each package.

JSON repositories are the only ones, supporting tags at the moment.

The Githb/GitLab/BitBucket user/repository providers just support (deprecated) branch based releases. They exist for backward compatibility reasons and to support adding any repo directly to Package Control' `"repositories": []` setting. Basically an alternative for cloning a repo into _Data/Packages/_ directory.

There's not enough context/information to know whether a repo contains multiple packages out of the box. For anything else we have `repository.json`.

**Comment by mataha** [comment]
Doesn't that ask for a configuration file inside a package though?

To put it in a broader scope, having a single source of truth would eliminate a lot of cruft in repositories... right now there are things like `.sublime-dependency`, `dependency-metadata.json`, `.hidden-sublime-package`, `package-metadata.json`, `.supports-a-file-icon-customization` (my personal favourite, welp), possibly more...

**Comment by deathaxe** [comment]
I don't see any relation with this feature request.

`.supports-a-file-icon-customization` is completely unrelated with Package Control.

The others are local files used to detect managed packages or dependencies.

**Comment by mataha** [comment]
What I'm trying to say is, what I believe we agree on, that one either needs:

- a configuration file inside a package, or
- an entry in the package registry

to successfully determine whether a repository contains subpackages or not.

None of the following heuristics would work as a package does not need any of them to be a package:

- Python script importing `sublime` or `sublime_plugin`
- `sublime-package.json`
- `.sublime-settings` file
- `.sublime-commands` file
- `.sublime-completions` file
- `.sublime-snippet` file
- `.sublime-menu` file
- `.sublime-build` file
- `.sublime-keymap` file
- `.sublime-mousemap` file
- `.sublime-syntax` file
- `.sublime-color-scheme` file
- `.sublime-theme` file
- `.hidden-color-scheme` file
- `.tmPreferences` file
- `.hidden-sublime-package`
- `.no-sublime-package`
- `.sublime-dependency`
- `dependencies.json`
- `dependency-metadata.json`

Maybe a `.sublime-project` file would work, but I feel that's too far-fetched.

**Comment by deathaxe** [comment]
Some config files are not the problem. But fulfilling this request would require fundamental changes to various aspects of how packages (and their releases) are to be handled when fetched from code hosters.

It's not worth it for the single mensioned use case of being able to install single syntax packages from sublimehq/Packages especially as such a thing would be solvable by a deployment script on the upstream repository (to repeat myself), which just would need to create zip files for each sub directory and provide a repository.json with explicit urls to them being published via github pages to provide a common download url. It would be much more flexible with regards to possible repository/folder structures without the need to struggle with it on the package control side of life.

I'd therefore close this as not planned.

**Comment by deathaxe** [comment]
Repos with multiple packages should build "sublime-packagge" files in a CI/CD workflow and provide them as "asset" based releases.
