### ISSUE TITLE
Disable package update message

### ISSUE THREAD

**Issue by 4sStylZ** [wbond/package_control#1231]
Hi,

I search a way for hide all the package update message. I have 70 packages and I am spammed each start by an update message.

I never read theses messages.

Is there a way for disable this feature without disable the auto-update ? I can’t find it on the documentation : https://packagecontrol.io/docs/settings

**Comment by wbond** [comment]
I personally don’t want to implement this feature because it would prevent Package Control from sending urgent messages to users.

I recommend you contact the authors of your packages and tell them to only write upgrade messages when necessary.

Alternatively you could propose changes to Package Control that ensure I can always send users messages as need be.

**Comment by 4sStylZ** [comment]
Hi, 

I understand you point of view because this is a pro tool when urgent security message are important.

Anyway, I found I way (because I prefer to lose 1% of urgent message than have to read 99% of message who I don’t give a f***) : 

https://stackoverflow.com/questions/29546017/how-to-suppress-package-control-messages-popup-in-sublime-text-3

* Install PackageResourceViewer from Package Control
* Open Resource via PackageResourceViewer -> Select Package Control
* Select package_control/package_manager.py to edit
* Comment out line self.print_messages(package_name, package_dir, is_upgrade, old_version, new_version) by putting a hash # in the front
* Save file.

---

The proper way seem’s to be multiple message level : 

* Urgent / security.
* New release /  important improvement.
* Informations / Changelog.

**Comment by madneon** [comment]
Can't we ignore messages from **specific packages**, the way one can configure ignored packages in global config?

File "Preferences.sublime-settings":
`	"ignored_packages": [...]`

**Comment by FichteFoll** [comment]
I'd actually prefer going the multiple level approach with urgent issues always being displayed and users being able to configure the level per package, in addition to a default level for all packages. The default for the default would be a level in the middle.

That would, however, require implementation of this, which I don't currently see, so being able to ignore messages from specific packages (while excluding Package Control itself) would be an easier yet unsatisfactory solution.

**Comment by seanhoughton** [comment]
The package update tab opens *over the top* of the current tab and steals focus. If you could just fix that problem it would make the annoying update messages much less annoying. The fact that it always shows up about 5 seconds after opening sublime text makes it particularly irritating because that's right about when I get to the point in a file I want to edit and start typing.

**Comment by FichteFoll** [comment]
Unfortunately, Sublime Text does not provide a way to open a new tab in the background. I don't think we have an upstream feature request for this yet at https://github.com/SublimeTextIssues/Core/issues, so unless you can find one, please feel free to create one.
