### ISSUE TITLE
Default settings not loaded when installing Sourcetrail package via Package Control

### ISSUE THREAD

**Issue by egraether** [wbond/package_control#1270]
If you are running into a bug, please read https://packagecontrol.io/docs/troubleshooting
before submitting an issue here.

Bug reports must include a debug log. The Troubleshooting page explains how to capture one.

------

We have a Sublime Text Package for communicating with our developer tool Sourcetrail: https://github.com/CoatiSoftware/sublime-sourcetrail

Manually installing the package by moving it into the `/Packages` directory works fine.
Manually creating an installed package via `Package Control: Create Package File` and then moving it into `/Installed Packages` works fine as well.
But when installing via `Package Control: Install Package -> Sourcetrail` there are errors because the default settings are not found:

```
...
Exception in thread Thread-9:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "SourcetrailPlugin in /Users/ebsi/Library/Application Support/Sublime Text 3/Installed Packages/Sourcetrail.sublime-package", line 65, in run
  File "./python3.3/socketserver.py", line 430, in __init__
  File "./python3.3/socketserver.py", line 441, in server_bind
TypeError: Can't convert 'NoneType' object to str implicitly
```

This error is caused by the missing setting `host_ip` that could not be retrieved from the settings.
If I delete my `Sourcetrail.sublime-settings` file in the manual install at `/Packages` then I get the same error.

**Note:** I never had any parallel installs that might interfere with each other.

This is the debug log when freshly installing the Sourcetrail package via package control:
[debug_log.txt](https://github.com/wbond/package_control/files/1321345/debug_log.txt)

I have no clue what's my mistake here and I can't seem to find anything online. Is it some naming issue maybe? Help is appreciated.

**Comment by egraether** [comment]
Fixed by adding `.no-sublime-package`. Not sure why that was necessary.

**Comment by wbond** [comment]
@egraether This is generally the wrong approach. That feature is designed for situations when you have a shared library or executable that must be extracted to be used.

Most likely the issue is that you have a race condition. It appears the issue is first seen when calling `on_activated()` as the plugin is loaded. My hunch is that at that moment in time, the `.sublime-settings` file from the zip file (aka `.sublime-package)` have not been added to the catalog, which is used by the settings subsystem.

I would probably have a check in `on_activated()` that sees if a host/ip is available, and if not, set a timeout to try again shortly. You could add a counter to ensure it doesn't try forever.
