### ISSUE TITLE
Validating remote folder... unknown error

### ISSUE THREAD

**Issue by rikkterdot** [wbond/package_control#1366]
None of the fixes I have read online or anywhere seem to work for me.

The only thing that changed on my end was a new internet plan and new router. Not sure if there are specific ports that sublime uses? Filezilla and such work fine.

I have sent 3 emails with debug logs over the course of 3 months and haven't gotten a response yet. This is REALLY hindering work flow and may be forced to go elsewhere.

**Comment by FichteFoll** [comment]
If this is about https://github.com/wbond/package_control/issues/38#issuecomment-402196806, then please close this issue as it's not relevant to Package Control. There are 182 people watching this repo because they are interested in Package Control issues, not SFTP issues.

I know it's frustrating not to receive answers, but this is not the right place. If you haven't received a reply to your email, you won't receive one here either.

**Comment by rikkterdot** [comment]
Clicked wrong item before making a new issue. Thanks! Sorry
