### ISSUE TITLE
[Feature request]: Ability to flag a package for the community

### ISSUE THREAD

**Issue by guylepage3** [wbond/package_control#1378]
@wbond, Love what you're doing sir..

I came across an [issue](https://forum.sublimetext.com/t/cannot-load-markdown-files-apparent-recursion-within-a-with-prototype-action-25000-context-sanity-limit-hit/36720/13?u=guylepage3) with a VERY popular package, [Java​Script​Next - ES6 Syntax](https://packagecontrol.io/packages/JavaScriptNext%20-%20ES6%20Syntax). I went to the packages web page on http://packagecontrol.io and looked for a way to "flag" or report that the package has errors in order to let others know but I did not see anything.

![image](https://user-images.githubusercontent.com/1711854/44592352-3fa87780-a78e-11e8-92cc-07d88c77b78f.png)

Feature request:
It would be nice to be able to flag a package in some way shape or form. Maybe adding a "red flag" icon with a counter beside it. or even a link to "report issue."

**Comment by bustbr** [comment]
This is an important issue, we need a way to flag malicious or otherwise problematic packages.

I recently stumbled across a package that contains quite dangerous code (in my opinion) and the maintainer refuses to fix it.
I'm looking for a way to report of flag it, because I think it shouldn't be available via Package Control in its current state. There seems to be no way to do that or somehow else warn the community though.

**Comment by deathaxe** [comment]
That's at least a request for packagecontrol.io not for Package Control client.

see: https://github.com/wbond/packagecontrol.io/issues

If malicious packages are identified, I'd recommend to file an issue at https://github.com/wbond/package_control_channel/issues or provide a PR for removal.
