### ISSUE TITLE
Random added to ignored packages on (un)install or update packages

### ISSUE THREAD

**Issue by kallookoo** [wbond/package_control#1379]
Do not copy debug logging, because it does not print any error.

Sometimes when you install or update a package after finishing the download and activation, the package is added to the ignored_packages list.

**Comment by kallookoo** [comment]
Any news about it?

**Comment by FichteFoll** [comment]
No. This issue is pretty hard to debug and likely involves races. If we had reliable reproduction steps, this might be fixable, but currently I believe the best way forward would be to rewrite like half of the package handling code to make it more robust, after finally dropping support for ST2, and I don't see anyone finding the time for that currently.
