### ISSUE TITLE
Package Control error 404

### ISSUE THREAD

**Issue by TuringsFlow** [wbond/package_control#1400]
I've installed ST3. Package control install package gives this error: 
"Package Control There are no packages available for installation".

On command line:

-`Package Control: Fetching list of available packages and dependencies
  Platform: windows-x64
  Sublime Text Version: 3176
  Package Control Version: 3.3.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.34.243
Package Control: Fetching list of available packages and dependencies
  Platform: windows-x64
  Sublime Text Version: 3176
  Package Control Version: 3.3.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.34.243
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug General
  Server SSL Certificate:
    subject: packagecontrol.io
    issuer: US, DigiCert Inc, www.digicert.com, RapidSSL RSA CA 2018
    common name: packagecontrol.io
    issue date: Tue, 29 May 2018 02:00:00 GMT
    expire date: Wed, 27 Nov 2019 13:00:00 GMT
Package Control: WinINet HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  User-Agent: Package Control v3.3.0
  Host: packagecontrol.io
  Connection: Keep-Alive
  Cache-Control: no-cache
  Accept-Encoding: bzip2,gzip,deflate
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 404 Not Found
  Server: nginx
  Date: Fri, 11 Jan 2019 18:13:24 GMT
  Content-Type: text/html; charset=UTF-8
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  Content-Encoding: gzip
Package Control: Skipping cache since the HTTP status code not one of: 200, 304
Package Control: Error downloading channel. HTTP error 404 downloading https://packagecontrol.io/channel_v3.json.
Package Control: Fetching list of available packages and dependencies
  Platform: windows-x64
  Sublime Text Version: 3176
  Package Control Version: 3.3.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.34.243
Package Control: WinINet HTTPS Debug General
  Re-using connection to packagecontrol.io on port 443 for request #1
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  User-Agent: Package Control v3.3.0
  Host: packagecontrol.io
  Connection: Keep-Alive
  Cache-Control: no-cache
  Accept-Encoding: bzip2,gzip,deflate
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 404 Not Found
  Server: nginx
  Date: Fri, 11 Jan 2019 18:13:24 GMT
  Content-Type: text/html; charset=UTF-8
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  Content-Encoding: gzip
Package Control: Skipping cache since the HTTP status code not one of: 200, 304
Package Control: Error downloading channel. HTTP error 404 downloading https://packagecontrol.io/channel_v3.json.
Package Control: No updated packages
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug General
  Server SSL Certificate:
    subject: packagecontrol.io
    issuer: US, DigiCert Inc, www.digicert.com, RapidSSL RSA CA 2018
    common name: packagecontrol.io
    issue date: Tue, 29 May 2018 02:00:00 GMT
    expire date: Wed, 27 Nov 2019 13:00:00 GMT
Package Control: WinINet HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  User-Agent: Package Control v3.3.0
  Host: packagecontrol.io
  Connection: Keep-Alive
  Cache-Control: no-cache
  Accept-Encoding: bzip2,gzip,deflate
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 404 Not Found
  Server: nginx
  Date: Fri, 11 Jan 2019 18:13:24 GMT
  Content-Type: text/html; charset=UTF-8
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  Content-Encoding: gzip
Package Control: Skipping cache since the HTTP status code not one of: 200, 304
Package Control: Error downloading channel. HTTP error 404 downloading https://packagecontrol.io/channel_v3.json.
Package Control: WinINet HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request
Package Control: WinINet HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 2 requests`

When I try to download https://packagecontrol.io/channel_v3.json, it returns a file without errors. How I can resolve it?

**Comment by Drew-Goddyn** [comment]
Getting same error, I imagine its related to the outage: https://github.com/wbond/package_control/issues/1398

**Comment by ITArtist** [comment]
Same error at both my PC and Mac. Seems like server problem.

**Comment by jorgeald77** [comment]
Since yesterday afternoon, I have the **same problem**.

**Package Control.sublime-settings -- User**
`{
	"debug":true,
	"bootstrapped": true,
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"A File Icon",
		"AdvancedNewFile",
		"Colorsublime",
		"DocBlockr",
		"DotENV",
		"Emmet",
		"Generic Config",
		"GitGutter",
		"Laravel 5 Artisan",
		"Material Theme",
		"Package Control",
		"PHP Companion",
		"SideBarEnhancements",
		"SublimeCodeIntel",
		"SublimeLinter",
		"SublimeLinter-php",
		"Syntax Highlighting for Sass",
		"Vuejs Complete Package"
	]
}`


**DEBUG / Package Control: Install Package**
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3176
  Package Control Version: 3.3.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.34.243
  Resolved IPv6: ::ffff:50.116.34.243
Package Control: Urllib Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Found previously exported CA bundle at /Users/jorge/Library/Application Support/Sublime Text 3/Packages/User/oscrypto-ca-bundle.crt (280016 bytes)
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
Package Control: Urllib HTTPS Debug General
  Upgrading connection to SSL using CA certs file at /Users/jorge/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
  Using hostname "packagecontrol.io" for TLS SNI extension
  Successfully upgraded connection to packagecontrol.io:443 with SSL Using TLSv1/SSLv3 with cipher ECDHE-RSA-AES128-GCM-SHA256
  Server SSL certificate:
    subject: CN=packagecontrol.io
    subject alt name: packagecontrol.io, www.packagecontrol.io
    expire date: Nov 27 12:00:00 2019 GMT
  Certificate validated for packagecontrol.io
Package Control: Urllib HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  If-None-Match: "5c37ea99-549b5"
  Accept-Encoding: bzip2,gzip,deflate
  Connection: Keep-Alive
  Host: packagecontrol.io
  If-Modified-Since: Fri, 11 Jan 2019 01:00:09 GMT
  User-Agent: Package Control v3.3.0
Package Control: Urllib HTTPS Debug Read
  HTTP/1.1 404 Not Found
  Server: nginx
  Date: Fri, 11 Jan 2019 20:07:42 GMT
  Content-Type: text/html; charset=UTF-8
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  Content-Encoding: gzip
**Package Control: Error downloading channel. HTTP error 404 downloading** https://packagecontrol.io/channel_v3.json.
Package Control: Urllib HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request

**Comment by meunal** [comment]
Please refer #1397 .

**Comment by djw4** [comment]
You can read more on #1398 or more directly; [forum.sublimetext.com/t/package-control-outage/41274](https://forum.sublimetext.com/t/package-control-outage/41274)

**Comment by wbond** [comment]
We should be back online now.
