### ISSUE TITLE
mac pro: install package error

### ISSUE THREAD

**Issue by AiPacinoDebug** [wbond/package_control#1422]
Package Control

There are no packages available for installation

Please see https://packagecontrol.io/docs/troubleshooting for help

macOS: 10.13.6 (17G65)
After reloading, the problem remains.

**Comment by mzTeamMeatMan** [comment]
Sublime Text
Unregistered

Copyright @ 2006-2019 Sublime HQ Pty Ltd
Version 3.2.1, Build 3207

**Comment by nusr** [comment]
+1 same macbook pro

**Comment by makbeaver** [comment]
I have the same problem :-(

**Comment by deathaxe** [comment]
This error message is primarily caused by Package Control failing to download required channel_v3.json, which contains the list of available packages.

There are various possible reasons:
- firewall blocking ST's plugin_host from accessing internet
- errors with CA bundle creation
- API changes of OS or used crypto libraries, ...

There are many reports about it with more information. Hence closing this one as duplicate.
