### ISSUE TITLE
HTML messages

### ISSUE THREAD

**Issue by jjb** [wbond/package_control#1459]
Thanks for a great project!

After installing the Nord Theme package, package control messages tab came up with nord theme messages in html. Are these supposed to somehow be rendered, or opened in a browser? or is this just a bug from the Nord theme?

**Comment by jjb** [comment]
I think I'm concluding it's a bug from the nord theme

**Comment by jjb** [comment]
https://github.com/arcticicestudio/nord-sublime-text

**Comment by FichteFoll** [comment]
Package Control messages are always shown as plain text. The Nord theme seems to have PC show its readme on installation but uses a lot of HTML tags in it, which are of course not readable by normal humans. In general, the readme appears to be generally unsuitable to be shown after installation because of the high HTML tag usage. You should open an issue at that repo and point this out to them.
