### ISSUE TITLE
Manually git-cloned deps are not accounted for in four-point-oh branch

### ISSUE THREAD

**Issue by rwols** [wbond/package_control#1550]
I have https://github.com/sublimelsp/lsp_utils checked out via git in $packages but it's not getting migrated:

```
Package Control: Error loading dependency metadata during migration - [Errno 2] No such file or directory: '/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/lsp_utils/dependency-metadata.json'
```

**Comment by rwols** [comment]
Maybe the question is should we also migrate these types of folders. Or let the users take of these cases themselves.

**Comment by deathaxe** [comment]
The bootstrapper needs the `dependencies-metadata.json` to successfully create the libraries meta-info so that it looks as the dependency was installed via pip. Not sure if we should try to migrate a repository as it can't be moved completely anyway. The other question was, which version info to use then.

Even though later on, you won't be able to git clone a dependency repo into the libs folder directly anyway. Means some more work is needed to handle such cloned deps. So tryiing to migrate them somehow might not be a good idea. It would leave the repo in the $packages path, which is probably not what we want.
