### ISSUE TITLE
[Question] Remove my plugins from the list 

### ISSUE THREAD

**Issue by kallookoo** [wbond/package_control#1598]
Hi,
Because not use any more the sublime text, what would be the best way to remove it from the list.
Thanks

**Comment by FichteFoll** [comment]
You can simply remove the references to them from the https://github.com/wbond/package_control_channel repository. However, if they still work fine and you just wish to cease maintaining them, you may want to consider adding a note to the readme about the state of the repository and leaving them be, since the ST API is pretty stable.

**Comment by kallookoo** [comment]
Thanks, 
But I prefer to delete them, I do not consider it correct to keep them if I no longer use them. Especially one that requires constant content updates.
