### ISSUE TITLE
Sublime (10061)

### ISSUE THREAD

**Issue by LowkeYFX** [wbond/package_control#1616]
When installing plugins, it gives error 10061. I changed WI-FI networks, turned off the firewall and antivirus - nothing helped.

"Unable to download Highlighter. Please view the console for more details.
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
ignored packages updated to: ["Base16 Color Schemes", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Attempting to use Urllib downloader due to WinINet error: Error downloading package. Connection refused (errno 12029) during HTTP write phase of downloading https://codeload.github.com/chriskempson/base16-textmate/zip/master.
Package Control: Error downloading package. URL error [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение downloading https://codeload.github.com/chriskempson/base16-textmate/zip/master.
error: Package Control".

Gonna be glad to get solution.

**Comment by deathaxe** [comment]
Can you download the file (https://codeload.github.com/chriskempson/base16-textmate/zip/master) via browser?

Error 100061 indicates the URL being unavailable or connection being rejected maybe due to certificate validation failure. Some network virus scanners are known to use man in the middle attacks to break up encrypted https traffic. If either the server or client detects it, connection is refused to prevent malicious content from being downloaded to the client machine.

**Comment by LowkeYFX** [comment]
![image](https://user-images.githubusercontent.com/96689528/152677955-73e20441-6f5c-40ca-b496-73324cd2aa3d.png)

**Comment by deathaxe** [comment]
Looks pretty much like someone is intercepting the HTTPS connection. Nothing Package Control could solve.
