### ISSUE TITLE
[four-point-oh] Uninstalling disabled packages only adds them to `in_process_packages`

### ISSUE THREAD

**Issue by FichteFoll** [wbond/package_control#1640]
I don't have much time to look into this further right now, but I wanted to report the issue already.

When I want to remove a package via PC that is currently disabled, it ends up in `in_process_packages` instead and will be enabled on the next ST restart.

**Comment by deathaxe** [comment]
Which revision of PC do you use? I can't reproduce this issue with latest revision, but it had been an issue at some point earlier this year.

Otherwise, which package is effected? Maybe some files are locked preventing it from being deleted from filesystem. PC has always re-enabled all in_process packages, which are found on filesystem aftar initial cleanup. PC doesn't know about the package having been disabled before removal started.

**Comment by FichteFoll** [comment]
One time specifically it occured on 7d0a8d69bd1ec1d34ed5be26c446ad7aac83fca7 (second to last commit) when I wanted to remove LSP-vue. It had previously been ignored but I wouldn't use it ever again, so decided to just uninstall it. Then, as I looked at my dotfiles repo, I noticed that while the package had been removed from the ignored packages it was still in the installed (and now also in-process) packages.

I'll try to reproduce it on my desktop machine on the latest commit.

All of this is on Arch Linux.

**Comment by deathaxe** [comment]
Do you see the packages present in `in_process_packages` vs. `ignored_packages` discrepancy right after removal or after next ST start?

It would be interesting, if the sublime-package file was removed and maybe re-installed after next start.

Would indicate some kind of race-condition somewhere, then. Not quite sure about possible causes though, as `in_process_packages` and `ignored_packages` settings are only updated one after another by PackageDisabler, before ...

https://github.com/wbond/package_control/blob/1ae62ad5738d5c4aedeeb723b8be68c3fc1aac4c/package_control/package_disabler.py#L284-L298

... and after ...

https://github.com/wbond/package_control/blob/1ae62ad5738d5c4aedeeb723b8be68c3fc1aac4c/package_control/package_disabler.py#L366-L381

a (batch of) package operation(s). They should therefore always be in sync.

**Comment by FichteFoll** [comment]
I wasn't able to reproduce this on my desktop. Will try to test again on my work machine when I find the time.

**Comment by deathaxe** [comment]
I've changed order of saving files when re-enabling packages to rule out Package Control.sublime-settings not being saved due to some package reloading going on.

A file remaining in both `installed_packages` and `in_process_packages` indicates _Package Control.sublime-settings. not having been saved for some reason.

**Comment by FichteFoll** [comment]
Forgot to test this/didn't get to it for the whole week. If I encounter the issue again, I'll reopen with hopefully more info.
