### ISSUE TITLE
Unable to install packages when using ZScaler 

### ISSUE THREAD

**Issue by WSF-SEO-AM** [wbond/package_control#1682]
On our end we are using Zscaler, and apparently some changes occurred and I can't install anymore packages.
Although I have created a bundle file collating three different certificate public keys, I keep receiving the same error message and no packages installed.

Can you please provide some support?

**Comment by deathaxe** [comment]
If you set `"debug": true` in Package Control settings, what is printed to console, when trying to install packages. Are there any certificate validation related issues or something along those lines?

Package Control relies on

1. wininet library on Windows, which fully handles TLS connections on OS-level.
2. python 3.8's urllib on Linux/MacOS, which uses ST's openssl 1.1.1 library for TLS connections.

In each case https://github.com/wbond/package_control/issues/1674#issuecomment-2117864576 applies.

**Comment by WSF-SEO-AM** [comment]
Thanks. Is there any particular order on how certificate files should be created?

**Comment by deathaxe** [comment]
Order doesn't matter.

Modified _Package Control.user-ca-bundle_ should get picked up each time PC detects it is newer than the auto generated merged CA bundle.

PC caches results and won't reach out to servers for meta data, once they are downloaded successfully. In that case restart may be required to force new downloads. But as long as those fail, updated CA bundles should be picked up.

But actually, you are better off adding additional CA bundles to your OS's cert store anyway. Otherwise other apps may also fail establishing trusted TLS connections with host name verification.

**Comment by deathaxe** [comment]
Package Control 4 actually uses openssl's default mechanisms to load default root certificate bundles via [load_default_certs(()](https://github.com/wbond/package_control/blob/c441c4e0d3ab7000827fb478079e3bda02cc387c/package_control/http/validating_https_connection.py#L63) method on python 3.8 and additionally loads user CA bundle afterwards.

The mechanism has been tested locally on Windows and Linux as well via Github Actions for all platforms, successfully.

If a misconfiguration or external security appliance is blocking required operations to establish a trustworthy connection, there's nothing which can be done by a client like Package Control.

**Comment by WSF-SEO-AM** [comment]
Apparently upon supplying the ZScaler certificate in the bundle file, the issue was resolved.
It didn't work at first, but I can only assuming I was using the wrong file at this stage.
We can close the issue.
