### ISSUE TITLE
New packages missing 

### ISSUE THREAD

**Issue by Excel66** [wbond/package_control#1690]
For some reason newer packages like LSP-some-sass and even older ones like Typescript and Typescript Compiler are not available for installation in the package list

**Comment by deathaxe** [comment]
_TypeScript_ packages has been disabled for ST4000+ 2 years ago, because
1. it is unmaintained, 
2. its auto-completions don't properly work on ST4 
3. and ST4 provides much better syntax highlighting for that languages

_TypeScript Compiler_ package is marked compatible with ST2 only and therefore not available for ST3 or ST4. Last change to that registration is over 11 years old.

_LSP-some-sass_ is available for ST build 4169+.

![grafik](https://github.com/user-attachments/assets/97b44cea-5217-49f5-8be6-8cd044449054)
