### ISSUE TITLE
SFTP: Validating remote directory fails

### ISSUE THREAD

**Issue by mciparelli** [wbond/package_control#38]
Cant connect to any FTP with plugin SFTP. Keeps on validating remote directory and wont connect. Could anyone tell me why could this issue be happening? Thanks

**Comment by solepixel** [comment]
@wbond Is there a place where I can find some troubleshooting steps to this issue? I also ran into this issue and can't find much regarding resolving this issue. My connection works in Filezilla, but not Sublime SFTP.

**Comment by appchap** [comment]
Having the same issue and cannot find a fix. This will lead me to stop using Sublime overnight if I cannot find a fix since this is a blocker for me and prevents me from working and earning the money!

Dreamweaver & Filezilla are working great. Sublime SFTP plugin (EACH PAID FOR!) says this> I have tried so much to get it working:

Connecting to FTPS server "*****" as "*****" ........... success
Validating remote folder "/." ........... failure (Disconnected)

IIS, Win 2012,

**Comment by wbond** [comment]
@appchap SFTP support is provided [over email](https://wbond.net/sublime_packages/sftp/support#Support). Also see https://wbond.net/sublime_packages/sftp/support#Generating_a_Debug_Log.

**Comment by nasospsa** [comment]
Having the  same error over here, and have also sent an email, but I thought I'd mention it here as well.

Thanks @wbond

**Comment by rikkterdot** [comment]
Same issue. Have sent 3 emails over course of 3 months and never getting a response.
