### ISSUE TITLE
Unable to use Package control after installation on Sublime Text 3

### ISSUE THREAD

**Issue by kajiatsushi** [wbond/package_control#532]
I installed package control via GIT install using terminal on 10.8.4

When I load up sublime text 3 afterwards, this message pops up

"
Package Control

Your system's locale is set to a value that can not handle non-ASCII characters. Package Control can not properly work unless this is fixed.

On Linux, please reference your distribution's docs for information on properly setting the LANG environmental variable. As a temporary work-around, you can launch Sublime Text from the terminal with:

LANG=en_US.UTF-8 sublime_text
"

**Comment by voidptr** [comment]
+1 benslice's solution. Explicitly unsetting LC_ALL fixes the problem in Arch with Sublime Text 3.

**Comment by mikeshultz** [comment]
For anyone still having this issue, try out the tips on `LC_CTYPE` and `LC_MESSAGES` in #1087.

**Comment by flip111** [comment]
I use CentOS 7 i tried the advise it doesn't work (i still get the warning dialog). When i check with `locale -a` i don't get `en_US.UTF-8` in the list, but i do get `en_US.utf8`. So i tried that locale instead but this also didn't work. Anyone know how to make this work with CentOS? Or possibly fedora or redhat since they are similar distros...

**Comment by alordiel** [comment]
I had this issue on Arch using KDE. Not able to start package manager due to this LC_CTYPE error. I tried most of the solutions I have found here and none have help me. My starting point of fixing it was to find why i do have problems with my `locale`. The issue was that when I have installed initially my OS i have set it as en_ZA locale. Then at some point have changed it to en_US and then the problems have started. I have tried to change locale.conf and locale.gen files but with no success. Then I found that I have set the format setting for the region in my system configuration (through System settings -> Regional Settings-> Formats -> Region) as `en_US`. Once I've changed it back to `en_ZA` and rebooted all was fixed. Just have no idea why editing the` /etc/locale` and running  `locale.gen` didn't work.
