### ISSUE TITLE
Package control won't load after upgrade to 3.0

### ISSUE THREAD

**Issue by dkebler** [wbond/package_control#817]
Per your message ran the console script for upgrade PC 3.0 in ST 3.0.    Upon restart package control not loaded (others loaded fine).  Checked installed packages directory it's there.  So removed that and resintalled via website script.  Still won't load.  Downloaded and manually copied PC package to installed packages, still no love.
Running ST3 build 3065 on Linux Mint (17.04, Unbuntu 14.04)

Do you still have 2.0 available for download in the event I can't resolve this.

**Comment by FichteFoll** [comment]
The script was only supposed to be run on Windows ST3 and won't work on Linux as there is no _ssl module.

Check the `"ignored_packages"` setting in your user settings file and remove Package Control in it.

@wbond, if you still can you might want to update the message so that it is more clear that this code should only be run on Windows ST3. I mean, most people just pick a few words in the first paragraph and assume they have to run it. Another option would be to make it fail early or just test if the machine is not Windows (with inline conditionals).

**Comment by wbond** [comment]
I've updated the command in 116ace4bfe7a8489c0036879c02f9826461bccd3 to fail unless run on Windows/ST3.

**Comment by FichteFoll** [comment]
That's even better.
