### ISSUE TITLE
Concerns with updating the zip loader

### ISSUE THREAD

**Issue by FichteFoll** [wbond/package_control#831]
So, I was working on #821 and fixed #820 along the line when I noticed that the loader package is disabled, then swapped with the new archive after 700ms and reenabled. This raised my concern: What if the loader package was updated during the time? Like, when a dependency was updated or when multiple dependencies are removed in short succession. In that case the outdated `-new` archive would undo all changes made.

Then there is also the following situation:
Because of #820, the loader package would never be swapped for me. That means that the old to-be-removed loader.py code of the removed dependency would still exist in the loader package. When the dependency gets installed again later it would add another e.g. `50-requests.py` file to the zip archive and ZipFile wouldn't complain, leaving us with two files of the same internal name. Yeah, it works.
Checking if the file already exists is trivial (`name in z.namelist()`) but just as you can not delete files you can not override or replace them either, meaning we'd have to do the swap thing again.

There needs to be a blocking way to swap the loader package contents for that reason, but the problem is that many operations in package control are asynchronous, namely enabling and disabling of packages (also because of ST2 being non-thread safe). Could we make this instantaneous for the loader package or would that break on ST2?

I mind end up writing some convenience function to synchronously remove files from the loader package, dis- and enabling included, because right now that seems like the best option.

I'd be interested in discussing this on IRC or any other medium with you, @wbond.

**Comment by FichteFoll** [comment]
Apparently, it turned out that disabling a package doesn't even free ST's file handles on Windows and `do_swap` fails with a PermissionError.

Since I assume this is for Windows only I'll work on an alternative here, but I don't have a Linux or OSX machine for testing here.

**Comment by wbond** [comment]
Hmm, let's try to pin down a way to reproduce this. From various comments on the issues you've opened, I think that some of the bugs you may be experiencing are only happening under specific situations.

Before I released 3.0, I tested updating the loader package on ST3 on Windows - hence the `do_swap()` function at https://github.com/wbond/package_control/blob/master/package_control/loader.py#L183-L187. That only really exists for Windows - neither OS X or Linux lock files. Now, it is certainly possible, and even likely that there are still bugs with it, but it is worth making sure we are specific about where we observe them so a bunch of time isn't spent trying to fix issues that don't exist.

ST2 shouldn't really factor into this discussion since it uses an unpacked loader and uses the code at https://github.com/wbond/package_control/blob/master/package_control/loader.py#L147-L151.

Let's try to pin down the exact sequence of events with ST3 on WIndows that causes an issue and grab a backtrace of that. Then we can figure out how to work around it.

**Comment by FichteFoll** [comment]
Most of the issues I ran into are fixed now, and would make it hard to actually run into the issue described in this topic now. The one case I can image to likely happen is if two packages are removed in quick succession however, in which case many bad things can happen. 

Probably every file existing twice (except for the first removed dep and the second only once) in `.sublime-package-new` and then an exception when the second `do_swap` is called since the file wouldn't exist anymore. I think I can take care of this though.

**Comment by wbond** [comment]
I added a lock to the loader operations in 8ea9ad667b555fce74dc7fccded9d59fbbcbd3f8 to prevent issues with multiple removals and/or a sequence of removal followed by one or more additions.

I also ended up fixing a bug with executing the loader code for any dependency after the first when running on ST3. The zip import mechanism used by `sublime_plugin` was caching the zip file listing, meaning that only the first call to `sublime_plugin.reload_plugin()` was working. You can see the changes in dd055c641882185eac57717267e3dc69a2d3e57e.

**Comment by FichteFoll** [comment]
I actually wondered why it worked in the first place since ST should be loading the zip at startup already and thus not even find the first file. Glad you found a better way.
