### ISSUE TITLE
Package Settings directories (and files) not created if spaces are in the name (Ubuntu 14.04 Sublime 3)

### ISSUE THREAD

**Issue by chrisgravel** [wbond/package_control#851]
Summary: It seems that the package control installations are not creating the default settings files in the directory ~/.config/sublime-text-3/<PACKAGE_NAME>. I have only noticed it with package names with spaces in them. I.e. SublimeLinter installs just fine, but "Xdebug Client" does not.

In depth info:
I've noticed this twice when installing "XDebug Client" package and then "Web Inspector" package for sublime editor. This leads me to believe the problem is coming from package_control.

The file for XDebug settings should be located here:
~/.config/sublime-text-3/Packages/Xdebug Client/xdebug.sublime-settings

The issue I had with Xdebug was initially I couldn't change a setting for the depth view of array variables. This was actually a problem with the settings file which I didn't realize at first. Other people got the same problem and that can be seen here: 
https://github.com/martomo/SublimeTextXdebug/issues/66

I found a fix for the issue with Xdebug settings and I posted it here:
https://github.com/martomo/SublimeTextXdebug/issues/128

The file for Web Inspector settings should be located here: 
~l/.config/sublime-text-3/Packages/Web Inspector 3/swi.sublime-settings

**Comment by wbond** [comment]
The path you are referencing, `~/.config/sublime-text-3/Packages/Xdebug Client/xdebug.sublime-settings` won't be created because Xdebug Client will be installed as a `.sublime-package` file in ST3.

However, I just installed the package and the menu entries (Preferences > Package Settings > Xdebug > Settings - Default/User) seem to work fine. Do they not work for you?

Obviously the user settings file will be blank until you add something to it.

**Comment by FichteFoll** [comment]
First, this is by design.

Second, you're seeing this because of a combination of a few misconceptions. Basically, ST3 changed the way that installed packages are handled in that it doesn't unpack them anymore and stores them in `Installed Packages/<package name>.sublime-package`. Sublime Text itself will be able to pseudo-open files by pointing them to where the exctracted package *would* be but does not allow you to edit them.

Either way, you are not supposed to edit the default settings anyway and instead override them using the user settings.

**Comment by chrisgravel** [comment]
That's good to know and interesting because the SublimeLinter installation created a directory in Packages (not just pseudo-opening a file). Also adjusting my user settings file for Xdebug did not change the options as I had expected and as wbond describes. 

Perhaps I jumped to conclusions too quickly, it's just that changing settings did not work for me with Xdebug until after I created the directory and copied the contents of the defaults into the file there. This is the assumption I came to after a lot of troubleshooting and google searches. (You can see this was a valid problem by many users for xdebug).

**Comment by wbond** [comment]
SublimeLinter is extracted into the `Packages/` folder because it has a file in the root of the package named `.no-sublime-package`.

I can't say for sure why the Xdebug settings aren't working, but I don't think it is related to Package Control. Just glancing at the Xdebug source code, it appears there is a fairly complex system of configuration loading that pulls form multiple places, including the package settings, project config, currently selected view and more. https://github.com/martomo/SublimeTextXdebug/blob/master/xdebug/config.py Perhaps there is a bug in there somewhere?

**Comment by chrisgravel** [comment]
Alright, well I will try to test it on another desktop when I can get my hands on one and I'll post back if I did indeed find something (I wonder if it might be something to do with my Linux distro). Anyways thanks for the quick responses, I'll close this for now since I don't have more definitive information. Cheers.
