### ISSUE TITLE
Upgrade prints "error" when there are no packages ready for upgrade

### ISSUE THREAD

**Issue by gerardroche** [wbond/package_control#878]
I think the console message could omit the "error" part of the message as it's not really an error.

The message:

```
error: Package Control

There are no packages ready for upgrade
```

**Comment by FichteFoll** [comment]
Sublime Text automatically prints the entire message to the console that is shown via `sublime.error_message` API (the dialog that pops up). It's also responsible for the leading "error:".

I suppose that PC could use the `sublime.message_dialog` API instead since it seems like the more reasonable one in this situation.

**Comment by wbond** [comment]
As of 7586cc8860a1836160c10be9ee086b3368a76123, the various command should now appropriately use `sublime.message_dialog()` and `sublime.error_message()`.
