### ISSUE TITLE
Add or document installing from console feature

### ISSUE THREAD

**Issue by NameFILIP** [wbond/package_control#883]
I want to create a script that installs a set of most popular packages for a Front end developer (Emmet, LESS, Sass, SideBarEnhancements, EditorConfig, etc).

In order to accomplish this, it would be nice to have an ability not only to Install Package by hands, but also from console or command line. Something like `PC.install_package("package_name/url")`

P.S. I guess such functionality more or less already exists, but not well documented.

**Comment by FichteFoll** [comment]
You are correct, such functionality exists in form of the [advanced_install_package](https://github.com/wbond/package_control/blob/c9034102844456c9c69ef13ac159d59d0de29833/package_control/commands/advanced_install_package_command.py#L22) command.

It's not documented on https://packagecontrol.io/docs/usage though.

**Comment by NameFILIP** [comment]
Sorry, unfortunately, my Python skills are not as good as Java or JavaScript. How do I use the `AdvancedInstallPackageCommand`?

I've tried running `AdvancedInstallPackageCommand.run(..)` in the Sublime's Console, but it returns `NameError: name 'AdvancedInstallPackageCommand' is not defined`

**Comment by wbond** [comment]
It isn't that I don't want to tell you the exact answer, but instead I encourage you to look at the ST docs here so you can learn more about Sublime Text. This will be useful if you are intending to build something on top of Package Control. https://www.sublimetext.com/docs/3/api_reference.html

**Comment by NameFILIP** [comment]
I've spend about an hour trying to figure out how to make it work. I would appreciate some guidance.

As I said, I am far from Python expert. The code that almost works:

```
import package_control.commands.advanced_install_package_command
package_control.commands.advanced_install_package_command.AdvancedInstallPackageCommand.run("Emmet, SideBarEnhancements")
```

The problem is that [here](https://github.com/wbond/package_control/blob/c9034102844456c9c69ef13ac159d59d0de29833/package_control/commands/advanced_install_package_command.py#L29) the first parameter is `self`. I've tried to pass `package_control.commands.advanced_install_package_command.AdvancedInstallPackageCommand` there, but unsuccessfully. So what should I pass there?

**Comment by FichteFoll** [comment]
I'll give you a few tips. Hopefully not too much, but it seems you are really missing the fundamentals.

First, the `self` parameter is the reference to the object instance in particular since this is a "bound" method. Pretty much like `this` in C++ and Java but more flexible. So, technically you would need to create a new instance first by calling the constructor (`__init__`, inherited from `sublime_plugin.WindowCommand`) and then call the `run` method of that object. However, this is not how commands work in Sublime Text.

So the second tip is: There are API functions to "run" commands. Commands are the main interface between anything that registers events and anything that does something in ST (key bindings, menu items, the command palette all use the "command interface"). Maybe [this](http://docs.sublimetext.info/en/latest/extensibility/commands.html) is worth a read.

And the final tip, command names of Python classes (that subclass a `sublime_plugin.*Command` class) are automatically converted to snake_case and the trailing `Command` is stripped, so the above command name would be converted to `advanced_install_package`, as indicated by my link text.

**Comment by deathaxe** [comment]
All major commands are available from command line in Package Control.

see: https://github.com/wbond/package_control/issues/1597#issuecomment-1418257315
