### ISSUE TITLE
Adding package-metadata.json to my plugin, causes it to be deleted

### ISSUE THREAD

**Issue by TundraTech** [wbond/package_control#900]
Title says it all...

My plugin is working great except when i try to a add the package-metadata.json file, package control deletes the entire plugin folder because it says it is "orphaned". This is a little scary because Im sure like many other dev's do when building a new plugin, you do it live in the packages folder so you can see what the heck is going on.

Well thank god i had a backup..seriously, this is a dangerous scenario and easily could have lost everything!

package-metadata.json contents:

{
	"url"         : "http://www.tundratech.ca",
	"description" : "Cleans junk from files!!!",
	"version"     : "0.1"
}

Pertinent log info on startup:

plugins loaded
SublimeLinter: debug mode: off 
found 13 files for base name Main.sublime-menu
Emmet: No need to update PyV8
Package Control: Removed directory for orphaned package Cleaner
Package Control: Skipping automatic upgrade, last run at 2015-03-06 15:59:23, next run at 2015-03-06 16:59:23 or after
unloading plugin Cleaner.Cleaner
found 13 files for base name Default.sublime-keymap
found 12 files for base name Main.sublime-menu

If i exclude the package-metadata.json file, the plugin works flawlessly, no console or load errors whatsoever.

Whats going on?

**Comment by FichteFoll** [comment]
`package-metadata.json` is supposed to be created automatically by Package Control **only**! I'll leave it to Will to provide the detals.

**Comment by TundraTech** [comment]
Ok, I've built two plugins now that are ready for publishing.. where do i typ ein meta data, why does the package-metadata.json work fine for my other plugin. Im confused :/

**Comment by FichteFoll** [comment]
Metadata is mostly read from your github repo, which you specify in [this](https://github.com/wbond/package_control_channel/) repo. See also [the docs on submitting a package](https://packagecontrol.io/docs/submitting_a_package).

I can't exactly tell why it "works" for your other package. Maybe it has a "wrong" filename.

**Comment by wbond** [comment]
The `package-metadata.json` is an internal file used by Package Control. It isn't documented anywhere because you aren't supposed to use it.

Some details of the current implementation: the metadata is created when a package is installed via Package Control. To sync package installs across machines, Package Control tracks installed packages via the `installed_packages` setting. If a package has a metadata file but is not in the installed packages list, that means the package had been installed via Package Control but was removed from a synced machine, thus the package needs to be removed.

Most likely in these cases you have a metadata file but you did not install via Package Control, so the package is not an n the installed packages list and is thus being deleted. If you installed the same package via Package Control, the metadata would be overwritten and it would be added to the installed packages list, and thus not cleaned up.
