### ISSUE TITLE
Package is missing from Package Control at times

### ISSUE THREAD

**Issue by farcaller** [wbond/package_control#903]
I have a bunch of random user repotrs filing bugs for the package missing from package control:

https://github.com/farcaller/DashDoc/issues/20

https://github.com/farcaller/DashDoc/issues/8

Is there anything that could be added to address the package visibility? I think the most common issue here is that the package was installed already (as I see no reason why it would miss from the install list otherwise).

**Comment by FichteFoll** [comment]
farcaller/DashDoc#20 seems to have happened due to a github problem. Nothing we can do about that besides wait. Your best bet is usually to quickly check the package on packagecontrol.io and see if there is a "missing" message.

farcaller/DashDoc#8 doesn't really say much.

Generally, there are only a few reasons why a package can go missing:

1. It was renamed or deleted on github → the url in package_control_channel is wrong.
2. There is a problem with github's API.
3. There is a problem with packagecontrol.io (i.e. downtime).
4. The package is installed already.
5. The package is not available for the ST version on that OS.

**Comment by wbond** [comment]
I think @FichteFoll has covered most of the things that can cause a user to think a package is unavailable.

The only other I can think of it the package being disabled. Then it would show up to the user, but also can't be installed. This tends to trip people up a lot. I'm going to contact Jon and see if he can add some info to the console on startup to help users diagnose things.
