### ISSUE TITLE
Proxy / Certificate issue

### ISSUE THREAD

**Issue by ritchiedalto** [wbond/package_control#906]
I've done a great deal of searching and haven't found the exact same set of error codes but have found similar issues. None seemed to have a resolution that I could latch on to or apply to my work environment. I apologize now if this has already been addressed. This stuff is out of my area, but I'm the one pushing Sublime Text use in my organization and I kinda need to help fix the problem or die trying :)

Windows 7 / ST 2 (portable) / Package Control 2

I believe the important part of the debug/console log is this:

(Host proxy.xxxx.xxxx.xxx:8080 returned an invalid certificate (_ssl.c:493: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed))

I can post the whole log if necessary.

I've changed our proxy name (above) to proxy.xxxx.xxxx.xxx:8080 because I'm not comfortable posting that information here. 

From my searching: error:14090086 seems to mean that the certificates on our proxy are out of date? Seems unlikely but I suppose it possible.

The "_ssl.c:493" is the part that doesn't appear in other posts, I haven't figured out what it means yet.

I've seen many posts outside this forum where python and something called pip have connection trouble with this certificate issue. In those applications, it looks like there is a way to disable the verification part of the certificate. Is that safe? And is that something we can do here?

Any discussion/advice on this is much appreciated, thank you.

-Ritchie

**Comment by wbond** [comment]
The `_ssl.c:493` indicates the error was raised from line 493 of the `_ssl.c` source code file that Python uses to generate the `_ssl.pyd` dll on Windows.

Without know more about how your proxy works, this is really just a guess:

I believe it is possible that something like the following may be going on:

 1. You make an outbound connection to packagecontrol.io
 2. Your proxy gets the connection request and makes its own secure connection to packagecontrol.io
 3. Your proxy presents its own certificate back to the Package Control connection so that it can intercept the traffic for filtering/security reasons
 4. Alternatively it could be trying to pretend it is packagecontrol.io and returning a fake certificate, which would also fail verification

Is there anyone in your IT department who could confirm how the proxy handles secure connections? You could also ask them if there is a certificate or CA certificate for the proxy that could be provided to you to allow secure connections to be verified.

Alternatively, do you know what brand and model proxy is being used?

**Comment by ritchiedalto** [comment]
I am in a military installation, so providing you that information (assuming they'd even provide it to me) is not possible. I have access to one person who might be able to think about the ideas/guesses you've outlined above. All of this IT is managed about 17 links up the chain from where I am, so I'll do some poking but for the most part, this is probably hopeless :/ For now I'll have to rely on manual installation of the packages that allow it.

Thank you Will (and for your email assistance the other day). I'll close this issue, even if there is any possibility of getting it resolved, it's going to take forever and a day.

-Ritchie

**Comment by wbond** [comment]
In the case you described, I would imagine that they are filtering/scanning connections. I would look and see if there is any info about a CA certificate for the proxy.

If you have any other software that makes successful connections outbound to packagecontrol.io or other sites, it is either not using SSL, not checking the certificates, or has the CA certificate available. You may be able to find it there.

**Comment by ritchiedalto** [comment]
Our web browsers seem to be the only thing that can do that, I can easily browse to packagecontrol.io and the connection is secured and verified. I was hoping that putting the user agent string in the config would set me free but it didn't do anything. Most likely I'd have to ask for an exception to be made, I'll save that headache for some other time :) Thanks again!
