### ISSUE TITLE
Website markdown parser

### ISSUE THREAD

**Issue by p3lim** [wbond/package_control#912]
There is an issue with the way the markdown parser on the website handles lists.

This is the original, on GitHub:
https://github.com/p3lim/sublime-toxin#options

On the website, the list is not displayed as a list:
https://packagecontrol.io/packages/Theme%20-%20Toxin

I'm aware that by proper markdown syntax, I should probably add a newline before the actual list, but GitHub handles it gracefully (and you could even use [GitHub's parser](https://developer.github.com/v3/markdown) if you wanted to)

**Comment by wbond** [comment]
There is actually a repository for the website, so this issue should be filed at https://github.com/wbond/packagecontrol.io/issues.

Unfortunately I can't use the GitHub parser because of the rate limit. With all of the other crawling activity, running every single md file through GitHub would cause me to hit the rate limit every hour.

GitHub used to release their Markdown parser as open source, however that is no longer the case. I haven't seen any information yet as to whether or not they are using CommonMark for markdown. If that is the case, I could use one of the newer CommonMark parsers. Currently I use misaka (https://github.com/wbond/packagecontrol.io/blob/master/app/lib/readme_renderer.py#L90-L120).
