### ISSUE TITLE
Only a few of packages are available (fresh install)

### ISSUE THREAD

**Issue by n3ps** [wbond/package_control#955]
Using Package Control v3.0.1 with fresh install of ST3 Build 3083.

Most of the packages are just simply "not there". For example, Emmet, SublimeLinter, etc. Also noticed that basically *ANY* package that starts with "D" and up are not listed.

I can probably install manually but that's not ideal.

Any ideas?

**Comment by KindOne-** [comment]
Yeah, I'm hitting the same thing. This just happened in the past ~20 minutes.

**Comment by zertosh** [comment]
A bunch of "B" packages are missing too. I don't see this chunk for example: https://github.com/wbond/package_control_channel/blob/7d310dc/repository/b.json#L4-L77

**Comment by MrMybach** [comment]
There is definitely something wrong. I experience the same problems on a fresh install.

**Comment by reado** [comment]
Same here.. just did a fresh install and I'm missing a ton of packages

Also noticed there was an error 
```
The dependency specified, bz2, is not available
```

Not sure if this is related.

**Comment by pilksahoy** [comment]
Same problem here.  It doesn't show any packages past those starting with a "C" for me.

**Comment by JohnBarry216** [comment]
Same here, and a co-worker is having this issue too. Not sure when it started but i just noticed it today. Can't see any packages past the "Copy Relative Path" package.

**Comment by CodeOfficer** [comment]
Same here. happening to me with SyncedSideBar.

**Comment by cody-sitegoals** [comment]
Same. Installed Sublime 3 (3092) and got the same error. OSX 10.10.2

>>> import urllib.request,os,hashlib; h = 'eb2297e1a458f27d836c04bb0cbaf282' + 'd0e7a3098092775ccb37ca9d6b2e4b7d'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by)
174110
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading Packages/Package Control/Package Control.sublime-settings
reloading plugin 0_package_control_loader.00-package_control
reloading Packages/User/Package Control.sublime-settings
Package Control: Installing 1 missing dependency
Package Control: The dependency specified, bz2, is not available
Package Control: No updated packages

After restart:

startup, version: 3092 osx x64 channel: dev
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/codyjenkins/Library/Application Support/Sublime Text 3/Packages
state path: /Users/codyjenkins/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/codyjenkins/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.23592
first paint time: 0.279455
startup time: 0.293217
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.run_all_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
plugins loaded
Package Control: Installing 1 missing dependency
Package Control: The dependency specified, bz2, is not available
Package Control: Skipping automatic upgrade, last run at 2015-06-08 16:16:07, next run at 2015-06-08 17:16:07 or after

**Comment by MojoJojo** [comment]
It seems like the list of packages is missing from the package control repository at https://packagecontrol.io/channel_v3.json

Not sure if its a version specific issue - perhaps a server side issue in publishing the plugins?

**Comment by PatHarryUX** [comment]
I'm having the same problem. Some packages are missing in "Install Package."

**Comment by XelaMon** [comment]
I am having this problem as well. I can't see past the "Copy Relative Path" package and am getting the dependency error. The debug log is below!

DPI scale: 1
startup, version: 3083 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/amarcell/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/amarcell/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/amarcell/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.0914543
startup time: 0.124454
first paint time: 0.125454
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
plugins loaded
Package Control: Installing 1 missing dependency
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3083
  Package Control Version: 3.0.1
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Resolved IP: 50.116.33.29
  Timeout: 30
Package Control: WinINet Debug Proxy
  proxy: 
  proxy bypass: 
  proxy username: 
  proxy password: 
Package Control: WinINet HTTPS Debug General
  Server SSL Certificate:
    subject: US, Massachusetts, Private Organization, 471714639, US, Massachusetts, Newbury, Codex Non Sufficit LC, codexns.io
    issuer: US, GeoTrust Inc., GeoTrust EV SSL CA - G4
    common name: codexns.io
    issue date: Tue, 16 Dec 2014 16:00:00 GMT
    expire date: Thu, 29 Oct 2015 16:59:59 GMT
Package Control: WinINet HTTPS Debug Write
  GET /channel_v3.json HTTP/1.1
  If-Modified-Since: Mon, 08 Jun 2015 19:20:02 GMT
  Accept-Encoding: gzip,deflate
  User-Agent: Package Control v3.0.1
  Host: packagecontrol.io
  Connection: Keep-Alive
  Cache-Control: no-cache
Package Control: WinINet HTTPS Debug Read
  HTTP/1.1 304 Not Modified
  Server: nginx
  Date: Mon, 08 Jun 2015 21:22:05 GMT
  Last-Modified: Mon, 08 Jun 2015 19:20:02 GMT
  Connection: keep-alive
  ETag: "5575eae2-30edb"
  Strict-Transport-Security: max-age=15552000
Package Control: Using cached content for https://packagecontrol.io/channel_v3.json from C:\Users\amarcell\AppData\Roaming\Sublime Text 3\Packages\User\Package Control.cache\01524fae79697630d0454ba3fabd9414
Package Control: The dependency specified, bz2, is not available
Package Control: Skipping automatic upgrade, last run at 2015-06-08 14:11:23, next run at 2015-06-08 15:11:23 or after
Package Control: WinINet HTTPS Debug General
  Closing connection to packagecontrol.io on port 443 after 1 request
Package Control: Fetching list of available packages
  Platform: windows-x64
  Sublime Text Version: 3083
  Package Control Version: 3.0.1

**Comment by overset** [comment]
@MojoJojo is correct - seems the repository is missing packages and out of sync and they do appear in the web search now - i.e. https://packagecontrol.io/search/emmet

Some packages were missing from the web search earlier so I'm assuming the https://packagecontrol.io/channel_v3.json cache has to catch up.

When it's back in sync it might be worth nuking the local package cache (in OSX):
`rm ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Package\ Control.cache/*` as per https://github.com/SublimeLinter/SublimeLinter-jshint/issues/4

**Comment by zhengbli** [comment]
Just found the TypeScript one is gone to.

**Comment by jimklo** [comment]
Looks like the cache only contains up to the middle of "C".

**Comment by kaped31** [comment]
The last package on my list is 'Copy Relative Path'

**Comment by saigemcvea** [comment]
Same problem

**Comment by dongerlel** [comment]
Same, can't install css3

**Comment by PhilipTrauner** [comment]
Same issue on a fresh install

**Comment by minhd** [comment]
Same problem. Can't install sublimeLinter. 
Did installed it on another machine just yesterday. Suspect it was caching issue so I reinstalled ST3 and wipe the packages. Same issue. 
It seems the packages are out of sync https://packagecontrol.io/channel_v3.json

**Comment by designorant** [comment]
Yep, https://packagecontrol.io/channel_v3.json it is.

**Comment by mikehdt** [comment]
Doing a fresh install last night, Package Control happily installed the bz2 dependency. This morning on a fresh install, it's failing to do so. Might this be related, or are such dependencies a different issue?

**Comment by wbond** [comment]
There is currently an issue affecting the default channel that is causing many packages and dependencies to be missing. Working on it as we speak.

**Comment by wbond** [comment]
Alright, should be fixed now

**Comment by designorant** [comment]
All fine now, indeed. Thanks @wbond!

**Comment by minhd** [comment]
Thanks @wbond . All good now

**Comment by reado** [comment]
Yay! Seems to be working for me!

**Comment by PauloSegundo** [comment]
There are still some missing packages. Ex: SublimeLinter-jshint

**Comment by JohnBarry216** [comment]
@PauloSegundo SublimeLinter-jshint is showing for me, though i did have to remove the package first. Do you already have that one installed?

**Comment by PauloSegundo** [comment]
My mistake... installed with lot other, using advanced install package and did't notice it was in the list. Sorry.

**Comment by CodeOfficer** [comment]
Is there a temporary workaround?

**Comment by wbond** [comment]
@CodeOfficer This issue was fixed. If you are having trouble with something, please open a new issue and be sure to include a debug log.
