### ISSUE TITLE
I can't install package-control 

### ISSUE THREAD

**Issue by developsoft** [wbond/package_control#964]
I've got this on the console:
There are no packages available for installation
Package Control: Urllib HTTPS Debug General
  Connecting to packagecontrol.io on port 443
  CA certs file at C:\Users\Paviliondm4\AppData\Roaming\Sublime Text 3\Packages\User\Package Control.merged-ca-bundle
Package Control: Error downloading channel. HTTP exception InvalidCertificateException (Host packagecontrol.io returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:547))) downloading https://packagecontrol.io/channel_v3.json.
Package Control: The dependency specified, bz2, is not available
Package Control: Skipping automatic upgrade, last run at 2015-06-22 12:39:03, next run at 2015-06-22 13:39:03 or after

**Comment by developsoft** [comment]
does anyone have some advice? 
thanks in advance...

**Comment by wbond** [comment]
It seems that something is messing with your connection to the internet, breaking the secure connection to the Package Control channel server.

If you visit https://packagecontrol.io in a browser, can you post a screenshot of the certificate information window? I'd like to check and see if the certificate is being manipulated.

**Comment by developsoft** [comment]
thanks for answering @wbond 
![error_certification](https://cloud.githubusercontent.com/assets/3177120/8387426/4f978222-1c26-11e5-8ad8-b4f35c6aeb57.png)
this is the kind of error.Actually, I was looking for another related posts , and following your explanations, I achieved to solve it. Copying the PEM code in the Package Control.system-ca-bundle, it worked!
It noticed that I avoid the error by copying the PEM code,but is there a way to fix the problem or is the only solution? just a doubt.

**Comment by wbond** [comment]
What this means is that someone is intercepting your traffic to packagecontrol.io. The only way to get around the error is to add their certificate as trusted - indicating you are alright with them seeing and modifying any data sent back and forth between your computer and the Package Control server.

However, if you have the PEM of the cert that is intercepting your traffic, add it to `Package Control.user-ca-bundle` since the `.system-ca-bundle` is periodically regenerated from your OS.
