### ISSUE TITLE
Force package control to re-read Package Control.sublime-settings?

### ISSUE THREAD

**Issue by dvcrn** [wbond/package_control#997]
Hello, I'm looking for a way to efficiently reload package control and trigger a re-read of all changes inside `Package Control.sublime-settings` without restarting sublime text. 

I played around with `imp.reload` but couldn't find a way to do this. I also tried the "cheese" method and used `os.rename` to rename `Package Control.sublime-package` into something else out of a st plugin but even that didn't trigger a reload. 

Any ideas how to achieve this?

**Comment by FichteFoll** [comment]
What is the root purpose of this?

**Comment by wbond** [comment]
@dvcrn Every time a new `package_control.PackageManager()` instance is created, the settings are loaded from Sublime Text's settings cache for `Package Control.sublime-settings`. You can refresh Sublime Text's cache by saving the file to disk, or using the `sublime.load_settings('Package Control.sublime-settings')`, manipulating the settings and then calling `sublime.save_settings()`. Package Control also caches fetched channel and repository information for a period controlled via the [`cache_length`](https://packagecontrol.io/docs/settings#setting-cache_length) setting.

`imp.reload` is used to reload Python code, however that doesn't sound like what you are trying to do. If for some reason you are, you should know that due to the current implementation of `sublime_plugin.ZipLoader()`, Python code inside of `.sublime-package` files is not properly refreshed, even if the package file changes. Package Control attempts to work around this for itself, however from some bug reports I have seen, it doesn't work in 100% of the situations.

**Comment by dvcrn** [comment]
Hey Will, thanks for the explanation. I tried to use `imp.reload` to reload entire Package Control with the hope that it would automagically do what I tried to achieve. I think I didn't explain enough what exactly I tried to do

I'm trying to get Package Control to do the same steps it does during restart of SublimeText:

- Read dependencies and packages
- Cleanup orphaned packages
- Install new packages
- Upgrade existing packages

... but without restarting ST. 

I played a bit around with `PackageManager()` and browsed through the code but couldn't find a performant way to get what I need. 

In your opinion, what would be the best approach for this? Is there any class I could ping / call that would cascade these changes?

**Comment by wbond** [comment]
Ah, I see. Well, the `PackageCleanup()` class is what does the cleanup and fires off the upgrade check. If you were to call it like https://github.com/wbond/package_control/blob/master/Package%20Control.py#L144, it would do what you want. The only catch is that it respects the last run time, and by default it will only check for upgrades if the last check was at least an hour ago.

**Comment by dvcrn** [comment]
This seems to do exactly what I was looking for. Works perfectly! Thanks for the swift replies!
